### ISSUE TITLE
Support "anonymous mode" for native downloader from AWS S3

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#1091]
**Is your feature request related to a problem? Please describe.**

Currently if the following conditions are met, the Rust native S3 downloader will fail with a MissingCredentials error:

1. Accessing data from a public bucket
2. No credentials provided in by user as `IOConfig`
3. No credentials provided on credentials discovery path on the host machine

However, this means that we cannot run our native downloader in environments without S3 credentials, such as Google Colab or in CI in GitHub actions.

**Ask:**

We should allow for "anonymous-mode" S3 access, which basically means that accessing data in an environment where there are no credentials being provided, but the data is being retrieved from a public bucket.

* s3fs supports this with the `anon=True` flag: https://s3fs.readthedocs.io/en/latest/
* boto3 supports this by creating the client with "UNSIGNED" signatures: `boto3.client("s3", config=Config(signature_version=botocore.UNSIGNED))`

**Comment by samster25** [comment]
closed by: https://github.com/Eventual-Inc/Daft/pull/1105
