### ISSUE TITLE
[IO] Reading back written Images from Parquet not preserving logical type

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#1149]
When writing logical types to Parquet, it appears that Daft strips logical type information because when reading back that same data from the written Parquet file, logical type information is lost.

Here is a reproducible example for images:

```python
import daft

PARQUET_PATH = "https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6.5plus/resolve/main/data/train-00000-of-00001-6f24a7497df494ae.parquet"

df = daft.read_parquet(PARQUET_PATH)
df = df.select(df["URL"])
df = df.select(df["URL"].url.download().image.decode().image.resize(32, 32).alias("image"))
df.limit(5).write_parquet("test.parquet")

df = daft.read_parquet("test.parquet")
df.collect()
```

**Comment by samster25** [comment]
This looks resolved now!

<img width="652" alt="image" src="https://github.com/user-attachments/assets/f4b82e06-fa89-4a81-859b-aacf13f46483">
