### ISSUE TITLE
[QueryPlanV2] V2 Planner working end-to-end against a selected test suite

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#1189]
Acceptance criteria:

Can run test suite with some variant of a command like `DAFT_PLANNER_V2=True pytest -m 'planner_v2_tdd'` which runs Daft using the new Rust-based planner, and all tests green

**Comment by clarkzinzow** [comment]
We can close this, since all Daft tests pass under the new query planner.
