### ISSUE TITLE
[IO] Parquet reader correctness checks

### ISSUE THREAD

**Issue by raghumdani** [Eventual-Inc/Daft#1217]
**Is your feature request related to a problem? Please describe.**
We are planning to use daft parquet reader to improve CDC efficiency in [DeltaCAT](https://github.com/ray-project/deltacat). As part of that we would like to ensure daft has necessary validation checks in place for correctness. 

**Describe the solution you'd like**
Daft should fail with validation error in below scenarios:
- The total number of rows in the Daft df does not match the `num_rows` in the parquet metadata.
- The total number of columns in the Daft df does not match the `num_columns` in the parquet metadata.
- (long term) The column statistics (null_count, min_max etc.) in the parquet metadata is not consistent with the daft DataFrame.   

**Describe alternatives you've considered**

**Additional context**

**Comment by jaychia** [comment]
Awesome, thanks @raghumdani!

I was thinking maybe a solution like:

```
*.read_parquet(validations=True)
```

Where we perform (potentially) expensive validations if the user requests it:

1. Check against [Parquet checksums](https://parquet.apache.org/docs/file-format/data-pages/checksumming/) if provided
2. Check min/max statistics if provided

Some of the checks should be pretty cheap, and we should be able to just do this every time:

1. Number of rows
2. Number of columns/types of columns

---

A good approach to this ticket could be to tackle the latter category first (cheap, easy validations). We can then add a `validations=True` flag if we anticipate a need for the more expensive validations-on-read such as checksumming and min/max values.

Let us know what you think!

**Comment by samster25** [comment]
Hi @raghumdani, just added some correctness checks (num rows and num columns) to https://github.com/Eventual-Inc/Daft/pull/1225
