### ISSUE TITLE
Add Conda release?

### ISSUE THREAD

**Issue by dizhouwu** [Eventual-Inc/Daft#1387]
Conda/Mamba env is very popular in real-world use cases as they are arguably more powerful than pypi. I think a conda release will accelerate user adoption?

**Comment by samster25** [comment]
Thanks @dizhouwu for making an issue! On the build side, we're currently working on adding a windows target for the next release. I also try publishing to conda for this week's release, is there a guide that you know of that we can follow to do so?

**Comment by dizhouwu** [comment]
Sorry I do not really have a guide..

**Comment by jimthompson5802** [comment]
@samster25   Is this what you are looking for?  
https://docs.conda.io/projects/conda-build/en/stable/user-guide/tutorials/building-conda-packages.html

**Comment by jaychia** [comment]
I think @GuyPozner actually made this happen! 

https://anaconda.org/conda-forge/getdaft
