### ISSUE TITLE
Add getter for Struct and List expressions

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#1389]
**Is your feature request related to a problem? Please describe.**

Expression indexing should work for both Struct and List types:

For structs:
```
col("struct_column").struct.field("foo")
```

For lists:
```
col("list_column").list.get(0, default=None)
```

This will return the specified `default` value if the specified index is out of bounds

**Comment by samster25** [comment]
@jaychia is this complete?

**Comment by jaychia** [comment]
> @jaychia is this complete?

No, cc @clarkzinzow who has a branch open I think

**Comment by kevinzwang** [comment]
Some questions:
- Do we want to enforce some sort of type consistency between the list type and the default type? How would we do this?
- Do we want to support negative indexing into lists?

**Comment by samster25** [comment]
> Would it be correct behavior for the resulting type of list.get to be the sum (as defined by impl Add for &DataType) of the list element type and the default parameter type?
The correct behavior should be using the child_type of the list. e.g if you have `List[Int64]`, the type should be Int64. The default should be inferred to that type.

> Do we want to support negative indexing into lists?
If it's not too hard to do!
