### ISSUE TITLE
windows10 install daft failed

### ISSUE THREAD

**Issue by futureflsl** [Eventual-Inc/Daft#1416]
I use pip install getdaft.it failed

**Comment by samster25** [comment]
Hi @futureflsl, Thanks for making an issue! I'm currently working on this right now and windows wheels should be released in a few days. Check https://github.com/Eventual-Inc/Daft/pull/1386 to follow closer

**Comment by samster25** [comment]
Hi @futureflsl, this should no be fixed in the latest release!
