### ISSUE TITLE
Security Address

### ISSUE THREAD

**Issue by SCH227** [Eventual-Inc/Daft#1477]
I may have found a security issue in latest version of Getdaft . Following responsible disclosure, is there an email or other private channel where I could share the details?
Thank you

**Comment by samster25** [comment]
Hi @SCH227,

Thanks for raising this issue up! Here is the email you can send security issues to: daft-security@eventualcomputing.com

**Comment by PratikDevlekar** [comment]
Hi @samster25,

I think it's better to Integrate an open-source vulnerability scanning solution into our workflow using GitHub Actions. 

I can pick this project up :)

**Comment by samster25** [comment]
That would be great! Thanks :)

Sent via Superhuman iOS ( ***@***.*** )
