### ISSUE TITLE
[CSV Reader] Support ignoring comments in CSVs.

### ISSUE THREAD

**Issue by clarkzinzow** [Eventual-Inc/Daft#1506]
Post-newline comments will currently be read as part of the first column's value in the following row. We should support allowing users to opt-in to ignoring post-newline comments, via supplying a single-byte comment-starting character that will cause all lines that start with that character to be skipped by the parser.

Arrow2's CSV reader already has an argument for such behavior via their reader builder: https://docs.rs/arrow2/latest/arrow2/io/csv/read/struct.ReaderBuilder.html#method.comment

**Comment by kevinmingtarja** [comment]
Hi, I'd like to take on this issue.
