### ISSUE TITLE
[CSV Reader] Support disabling double quote escapes

### ISSUE THREAD

**Issue by clarkzinzow** [Eventual-Inc/Daft#1507]
Our CSV reader currently interprets double quotes as escapes; we should allow this behavior to be disabled.

Arrow's CSV reader already supports this behavior via it's reader builder: https://docs.rs/arrow2/latest/arrow2/io/csv/read/struct.ReaderBuilder.html#method.double_quote

**Comment by ravern** [comment]
I can pick this up!
