### ISSUE TITLE
[CSV Reader] Support custom quote character.

### ISSUE THREAD

**Issue by clarkzinzow** [Eventual-Inc/Daft#1509]
Our CSV reader uses the double quote character (`b'"'`) as the default quote character, but a user may want to use the single quote as the quote character instead. We should expose an optional argument to override this default quote character.

Arrow2's CSV reader already has an argument for such behavior via their reader builder: https://docs.rs/arrow2/latest/arrow2/io/csv/read/struct.ReaderBuilder.html#method.quote

**Comment by kisharnath** [comment]
I'm excited to dive into contributing to Rust, even though I'm more familiar with Python. I'm ready to take a shot at it and would appreciate it if you could assign me all the "Good First Issues" to get me started.

**Comment by jaychia** [comment]
Hi @kisharnath, feel free to take a stab at any of the Good First Issues!
