### ISSUE TITLE
[CSV Reader] Set better buffer/chunk size defaults for local reader.

### ISSUE THREAD

**Issue by clarkzinzow** [Eventual-Inc/Daft#1512]
We currently use the same default buffer/chunk size configurations for both the cloud reader and the local reader, but they are currently tailored to the cloud reader. We should do some benchmarking for the local reader and set some more tailored local reader defaults.

**Comment by colin-ho** [comment]
Closed with new local csv reader: https://github.com/Eventual-Inc/Daft/pull/3055
