### ISSUE TITLE
Empty result crashes app

### ISSUE THREAD

**Issue by dioptre** [Eventual-Inc/Daft#1518]
**Describe the bug**

Receive:
```
DaftError::ValueError Need at least 1 series to perform concat
```

**To Reproduce**
Get an empty table on to_arrow or ...

**Expected behavior**
return an empty arrow table etc.

**Comment by jaychia** [comment]
Thanks for raising this @dioptre!

I just some naive attempts at reproduction:

```python
import daft

daft.from_pydict({"foo": []}).to_arrow()
daft.from_pydict({"foo": [1, 2, 3]}).where(daft.col("foo") > 5).to_arrow()
```

These seem to work fine, but do you have an example/quick pointers as to how I might be able to reproduce this issue?

**Comment by dioptre** [comment]
I'm using empty parquet files - let me see if I can get you one!

**Comment by jaychia** [comment]
Hi @dioptre ! Any chance you had a chance to find the offending files for this issue 😛 ?

**Comment by dioptre** [comment]
Argh I coded up a workaround by reading the parquets myself so its fallen off the radar - pretty sure its still an issue though.

**Comment by jaychia** [comment]
> Argh I coded up a workaround by reading the parquets myself so its fallen off the radar - pretty sure its still an issue though.

Actually -- yes I was able to read an empty parquet file and reproduce it :) 

Will dig in for a fix!

**Comment by jaychia** [comment]
Thanks @dioptre! Fix is merged and will be released in the next release :)
