### ISSUE TITLE
Back again: daft io_glob bug

### ISSUE THREAD

**Issue by marsupialtail** [Eventual-Inc/Daft#1520]
**Describe the bug**
daft.daft.io_glob does not work somestimes. 
daft.__version__
'0.1.20'
Ubuntu, x86 

Here's the problem. I have some files under s3://cluster-dump/big_hadoop/split_0/
daft.daft.io_glob("s3://cluster-dump/") works and returns files
daft.daft.io_glob("s3://cluster-dump/big_hadoop/split_0/") works and returns files
daft.daft.io_glob("s3://cluster-dump/big_hadoop/") returns empty!

I need to do the last command to figure out how many splits there are.

**Comment by jaychia** [comment]
Currently `daft.daft.io_glob` should **only** return files!

We are unable to return directories because of the algorithm that we use (falling back onto prefix-listing does not return "directories").
