### ISSUE TITLE
Getting 'DaftError::ArrowError External format error: Operation would exceed memory use threshold'

### ISSUE THREAD

**Issue by dioptre** [Eventual-Inc/Daft#1551]
**Describe the bug**
Can't convert daft to arrow, also fails on collect

**To Reproduce**
Using 2x 7.5MB parquet files

**Comment by jaychia** [comment]
Hi @dioptre! Thanks for making an issue

- What version of Daft is this running?
- Is there a chance you could share the parquet files that are causing this issue

I looked a little into the error message, and it seems that we currently allocate a maximum of 4MB per page when decoding Parquet pages.

It is likely that your files have some data that exceeds this, which is quite unusual given that most writers should be relatively well behaved and try to keep page sizes at about a default of 1MB. Is there some chance you can share the data that produced this error, or maybe share if a single cell (item form a row in a column) in your data could exceed 4MB?

**Comment by dioptre** [comment]
Thanks @jaychia I sent a link to the files to your personal gmail.

0.1.20 is the version

They were written by a third party, the data includes some mongo database backup.

It's very unlikely that a single cell could exceed 4MB but we'd like to support this.

**Comment by dioptre** [comment]
Also can confirm I tried 3 other loading libraries and all worked except daft.

```import pyarrow.parquet as pq``` was ok to compare

**Comment by jaychia** [comment]
> Also can confirm I tried 3 other loading libraries and all worked except daft.
> 
> `import pyarrow.parquet as pq` was ok to compare

Thanks! I just managed to confirm that one of the files had a huuuuge 15MB page. This was likely the cause of the issue. 

I'll go ahead and bump our page max size limit to be much higher. Look out for a release later today!

**Comment by dioptre** [comment]
Thanks!

**Comment by dioptre** [comment]
I think this probably relates to my last question - would love to cap the size of parquet files - not the size of cells. Would be great to arbitrarily limit the Parquet size to 1GB etc. and leave the page size to whatever is available in memory.
