### ISSUE TITLE
SQL to Daft

### ISSUE THREAD

**Issue by ammarar** [Eventual-Inc/Daft#1560]
**Is your feature request related to a problem? Please describe.**
There is a large friction when I want to get SQL data into Daft. We use [Trino](https://trino.io/) as our query engine for our data warehouse. We also use [Trino python client](https://github.com/trinodb/trino-python-client) to read data.

**Describe the solution you'd like**
I would like to have a `daft.from_sql(sql: str, connection)` function, which given the SQL and connection object, it is able to execute the SQL (in a data partitioned way) and return a `Daft.DataFrame`.

**Describe alternatives you've considered**
1. Ray Data: we tried using Ray Data, but the problem with it is that it doesn't work in a notebook (if you do ray_data.take(1) it crashes). So the iteration cycle is not going to be pleasant to our DS and MLEs.
2. SQL to pydict or pylist to Daft: more friction and non data partitioned.
3. SQL to S3 to Daft: more friction, but works. The friction being that users have to setup their s3 buckets and then having permissions to read and write (from Trino). Then run the SQL, then read parquet from Daft.

**Comment by jaychia** [comment]
It looks like Rust might have really good support for this via the connectorx create: https://docs.rs/connectorx/latest/connectorx/

It's really nice because we get native support for partitioning etc which will give us a mechanism for parallelism beyond naively using OFFSET/LIMIT, which is what Ray Data does.

**Comment by ammarar** [comment]
@jaychia looks cool. However, I couldn't understand how it figures out the relationship between the data partition and memory. Some partitions are too big and needs to be partitioned further, while others can be small enough to fit multiple data partitions into a single machine..
