### ISSUE TITLE
Improve Error message when calling aggregation method on dataframe without any columns

### ISSUE THREAD

**Issue by samster25** [Eventual-Inc/Daft#1583]
Currently when run an aggregation function on a dataframe without input columns:
```
df = daft.from_pydict({"x": [1,2,3]})
df.count()
```
we get the following error message, which is not very helpful.
```
AssertionError: no columns were passed in
```
We should instead: 
1. run the aggregation on all columns
2. give a better error that give an example 
3. tell the user to look for `df.count_rows()` instead.

**Comment by colin-ho** [comment]
I can take this!
