### ISSUE TITLE
Add APIs like df.groupby.apply(udf) or df.apply(udf) that give greater freedom

### ISSUE THREAD

**Issue by ztsweet** [Eventual-Inc/Daft#1630]
refer to
- [polars.map_groups](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.map_groups.html#polars-map-groups)
- [polars.dataframe.group_by.GroupBy.map_groups](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.dataframe.group_by.GroupBy.map_groups.html#polars.dataframe.group_by.GroupBy.map_groups)

**Comment by samster25** [comment]
Hi @ztsweet,

Good feature request! One question i have is that can we always expect the output of `map_groups` to be a single row?
