### ISSUE TITLE
Committing to Daft

### ISSUE THREAD

**Issue by suriya-ganesh** [Eventual-Inc/Daft#1634]
I was working on #1606  and have a patch ready. But, when the git hooks run. I'm getting multiple errors like this.

```error: this function has too many arguments (10/7)
  --> src/daft-csv/src/metadata.rs:21:1
   |
21 | / pub fn read_csv_schema(
22 | |     uri: &str,
23 | |     has_header: bool,
24 | |     delimiter: Option<char>,
...  |
31 | |     io_stats: Option<IOStatsRef>,
32 | | ) -> DaftResult<(Schema, usize, usize, f64, f64)> {
   | |_________________________________________________^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#too_many_arguments
   = note: `-D clippy::too-many-arguments` implied by `-D warnings`
```

Is there a way to skip this for now, or should I wait for the PR that makes these arguments as structs?

**Comment by jaychia** [comment]
Feel free to add `#[allow(clippy::too_many_arguments)]` to unblock yourself first!

Looks like a style lint issue snuck in during our last PR, fixing it right now :)

**Comment by jaychia** [comment]
Incoming fix: https://github.com/Eventual-Inc/Daft/pull/1635
