### ISSUE TITLE
daft cannot handle _metadata

### ISSUE THREAD

**Issue by braindevices** [Eventual-Inc/Daft#1659]
**Describe the bug**
when there is _metadata, daft treat it as normal data file and raise error about missing row groups.
v0.2.3

**To Reproduce**
```
import shutil
import os
import pyarrow as pa
import pyarrow.parquet as pq
t1 = pa.Table.from_pydict({"field1": ["a", "b", "c"]})
t2 = pa.Table.from_pydict(
    {
        "field1": ["d", "e", "f"]
    }
)
path = "/tmp/test3.pq"
shutil.rmtree(path, ignore_errors=True)
schemas = []
metadatas = []
for _t in [t1, t2]:
    schemas.append(_t.schema)
    pq.write_to_dataset(
        _t, 
        root_path=path,
        metadata_collector=metadatas
    )
pq.write_metadata(
    schemas[-1],
    f"{path}/_common_metadata",
)
pq.write_metadata(
    schemas[-1],
    f"{path}/_metadata",
    metadata_collector=metadatas
)
import daft

daft.read_parquet(path).to_pydict()
```
ValueError: DaftError::External Unable to create arrow chunk from streaming file reader/tmp/test3.pq/_metadata: External format error: File out of specification: Invalid thrift: protocol error

**Expected behavior**
should just work
**Screenshots**

**Comment by samster25** [comment]
Hi @braindevices! Thanks for making an issue.

I just ran your code and it looks like `/tmp/test3.pq` is a directory. is that expected? 

```
In [7]: ls /tmp/test3.pq/
1db50d2da7324203be646a84a97ef1bf-0.parquet  _common_metadata
65c175493f274598bdc2c1c88d66d2c5-0.parquet  _metadata
```
Currently we don't filter out files by extension so this 
`daft.read_parquet("/tmp/test3.pq/**.parquet").to_pydict()` works

**Comment by jaychia** [comment]
Oh, is this because the folder was created by Spark? I think Spark does some shenanigans with dumping a `_metadata` file by default.

**Comment by samster25** [comment]
I found this [write up ](https://github.com/apache/arrow/blob/43f4c286fef92b709853eefef207a50aefd9f5d3/docs/source/python/parquet.rst#writing-_metadata-and-_common_metadata-files) from pyarrow

**Comment by braindevices** [comment]
> Oh, is this because the folder was created by Spark? I think Spark does some shenanigans with dumping a `_metadata` file by default.

Yes, so far spark and dask are doing this. The example just tries to mimic the results without other dependcies.

Since you mentioned the wildcard works then it should be fine for a while. But I guess this is kind of standard, maybe we can skip them by default.

**Comment by braindevices** [comment]
The separated metadata has some advantage when you have lots of partition files. Then it can just obtain the info from a single file instead of crawling through the FS.
