### ISSUE TITLE
[CSV Reader] Support `YYYY/MM/DD` date formats.

### ISSUE THREAD

**Issue by clarkzinzow** [Eventual-Inc/Daft#1674]
The [current CSV reader](https://github.com/Eventual-Inc/Daft/blob/12bd49965901977606e0a3d241a1aec630ea9a9e/src/daft-decoding/src/deserialize.rs#L236-L240) supports `YYYY-MM-DD` date formats (the default format for `s.parse::<chrono::NaiveDate>()`), but does not support the `YYYY/MM/DD` format. We should add support for the latter by attempting to parse with both formats, and returning the parse date if either succeed.

## Implementation
Similar to our multi-format datetime parsing, we can use [`chrono::NaiveDate::parse_from_str(s, fmt)`](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDate.html#method.parse_from_str) + mapping over a list of supported formats, short-circuiting on the first success.

```rust
        Date32 => deserialize_primitive(rows, column, datatype, |bytes| {
            to_utf8(bytes)
                .and_then(|s| {
                    const items = &["%Y-%m-%d", "%Y/%m/%d"];
                    items.iter().find_map(|fmt| chrono::NaiveDate::parse_from_str(s, fmt).ok())
                 })
                .map(|x| x.num_days_from_ce() - temporal_conversions::EPOCH_DAYS_FROM_CE)
        }),
```

**Comment by murex971** [comment]
@jaychia @clarkzinzow  this issue has been resolved in #1523
