### ISSUE TITLE
`not_null` expression 

### ISSUE THREAD

**Issue by samster25** [Eventual-Inc/Daft#1720]
We have an expression for `is_null()` but we should have one for `not_null()` this is especially useful when doing io where we just care about expressions that are not null

**Comment by ThanhChinhBK** [comment]
hi, could I work on this issue?

**Comment by jaychia** [comment]
Hi @ThanhChinhBK !

Feel free to give it a stab :)

```python
# Keeps only rows where column "foo" is not null
df = df.where(col("foo").is_not_null())
```

It would probably be cleanest to implement an actual Rust expression for this, similar to our `Eq` and `NotEq` expressions. 

Let us know if you need any help getting started!

**Comment by ThanhChinhBK** [comment]
@jaychia thank you for after editting the code in src, I use the command `make build` but the python stub files aren't updated, could you help me on this?

**Comment by jaychia** [comment]
Hi! Our pyi stub files are updated manually!

--
Jay Chia
Founder, Eventual ( https://www.eventualcomputing.com/ )
Book a meeting with me ( https://calendly.com/jay-eventual/30min )

**Comment by samster25** [comment]
@colin-ho Do you want to look into doing this one next?

**Comment by colin-ho** [comment]
sounds good!
