### ISSUE TITLE
Getting hyper error connecting to s3

### ISSUE THREAD

**Issue by dioptre** [Eventual-Inc/Daft#1747]
We are getting this random error (more than) occasionally:

[aws_smithy_client.hyper_ext,None:221] [WARNING] unrecognized error from Hyper. If this error should be retried, please file an issue. err=error trying to connect: bad certificate format: bad certificate format (hyper::Error(Connect, Error { code: -9808, message: "bad certificate format" }))

While pulling from "s3://"

Weird as we are using verify_ssl=False, check_hostname_ssl=False,

**Comment by samster25** [comment]
Hi @dioptre,

Thanks for making an issue! Have a few questions:

1. Does this error error out the read or is it just logging the message out and retrying?
2. Also what S3 endpoint are you using, AWS or some private endpoint?
3. What OS is this happening on?

**Comment by dioptre** [comment]
1. errors out
2. s3
3. Mac/Darwin

**Comment by samster25** [comment]
@dioptre Are you using an M1 Mac? Is so can you reply with the output of the following commands (where python is the shell you used):

`file $(which python3)`

as well as `python -m sysconfig`

**Comment by jaychia** [comment]
Hi @dioptre ! Wondering if this issue can be closed/are you still seeing this in production?
