### ISSUE TITLE
Support for `sample`

### ISSUE THREAD

**Issue by ammarar** [Eventual-Inc/Daft#1759]
**Is your feature request related to a problem? Please describe.**
I want to get a sample of data to visualize using matplotlib, however, because I have too many records I want to get a good sample to visualize the data distribution.

**Describe the solution you'd like**
I want a function `sample(..)` that can sample a dataframe and return a dataframe with much smaller dataframe.

**Describe alternatives you've considered**
1. I can convert from Daft to Pandas or other dataframe, but that would not be scalable if the data is too large.
2. I can use where, but that would require me to implement a solution that may not be correct.

Spark: https://spark.apache.org/docs/3.1.2/api/python/reference/api/pyspark.sql.DataFrame.sample.html
Pandas: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sample.html

**Comment by samster25** [comment]
Hi @ammarar,

Thanks for making an issue for this! Would you be okay the Spark API for this? `sample(withReplacement=None, fraction=None, seed=None)`. If so, it should be fairly straight forward and performant since we can sample each partition individually. Let me know if that works!

**Comment by ammarar** [comment]
@samster25 Yeah the Spark API looks good to me. Thanks!
