### ISSUE TITLE
Populate table statistics when reading from Iceberg

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#1798]
**Is your feature request related to a problem? Please describe.**

Currently when reading data from Iceberg, Daft will not read statistics from Iceberg and insert them into the constructed MicroPartition:

https://github.com/Eventual-Inc/Daft/blob/main/src/daft-scan/src/python.rs#L295

This means that when any work needs to be done, Daft will have to read statistics from the Parquet files instead of using statistics provided by Iceberg, which incurs an additional hop to the Parquet files' metadata

**Acceptance Criteria**

We should correctly parse statistics provided by Iceberg and populate the stats in our MicroPartition.

**Comment by Fokko** [comment]
This would be great. This will avoid an additional call to the object store by fetching the Parquet footer.

There are a few things to look out for:

- The statistics might be missing for one or more columns. This can be [configured](https://iceberg.apache.org/docs/latest/configuration/) by setting table properties. By default, it only collects the statistics of the first 100 columns (`write.metadata.metrics.max-inferred-column-defaults`). Text and other long fields are truncated if they are longer than 16 characters, but this can be configured as well on a table or column basis (`write.metadata.metrics.default`).
- If you truncate utf8, you have to make sure that it is still valid utf8. Eg, you cannot just take the first 16 bytes.

**Comment by samster25** [comment]
Thanks @Fokko, Daft does support partial statistics in the case that some of the column stats may be missing but that is a good call out.

Can we also assume the truncated strings are valid UTF-8? Or should we run our own validation and pruning during decoding?

**Comment by jaychia** [comment]
After offline discussion, this issue with not be prioritized:

1. With the implementation of #1800, PyIceberg will be able to perform file-level pruning already
2. Daft performs rowgroup-level pruning at the Parquet level in our MicroPartitions

With those two, we don't actually need this feature since both file and rowgroup level pruning are already achieved. Archiving this issue!
