### ISSUE TITLE
Support `"A" in df` expression

### ISSUE THREAD

**Issue by skrawcz** [Eventual-Inc/Daft#1813]
**Is your feature request related to a problem? Please describe.**
it's common for dataframe libraries to support checking whether a column exists in the dataframe by doing:

```
col = "A"
if col in df:
   ...
```
Daft doesn't support that.

**Describe the solution you'd like**
Support `col in df`.

**Describe alternatives you've considered**
You could do `col in df.column_names` but I'm trying to build something generic that works for various dataframe libraries with [Hamilton](https://github.com/dagworks-inc/hamilton).

**Additional context**
N/A

**Comment by jaychia** [comment]
Thanks @skrawcz! We'll take a look at this and let you know when it's released
