### ISSUE TITLE
Disallow glob paths with `**` that is not a folder segment

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#1820]
**Is your feature request related to a problem? Please describe.**

Daft currently only correctly understands the `**` recursive wildcard when it is applied to a folder segment. I.e.

* `s3://bucket/**.csv` is not valid
* `s3://bucket/**/*.csv` is valid and conveys the intended behavior

We should provide an appropriate error message when we detect the former, or perhaps sanitize the input when we find instances of `**` not enclosed by `/`.

**Comment by nemo-1999** [comment]
I would like to work on this

**Comment by nemo-1999** [comment]
take

**Comment by conradsoon** [comment]
hey, i'd like to give this a shot :)
