### ISSUE TITLE
Improve Pretty Print of DataFrame for Notebooks

### ISSUE THREAD

**Issue by samster25** [Eventual-Inc/Daft#183]
**Is your feature request related to a problem? Please describe.**
Currently when we print a dataframe in a notebook, theres no cell boundaries or style.
<img width="346" alt="image" src="https://user-images.githubusercontent.com/2550285/190031367-610a1275-0f4d-4204-9b07-cebfaf917e50.png">

**Describe the solution you'd like**
Adding some CSS in repr_html similar to [pandas or polars](https://github.com/pola-rs/polars/blob/master/py-polars/polars/_html.py) would greatly improve readability.

<img width="198" alt="image" src="https://user-images.githubusercontent.com/2550285/190031507-14fbc6f9-0f83-415c-9aea-eab64b3c6039.png">

**Comment by jaychia** [comment]
Done in: https://github.com/Eventual-Inc/Daft/pull/205
