### ISSUE TITLE
[BUG] Physical plan breaking 50% of the time

### ISSUE THREAD

**Issue by dioptre** [Eventual-Inc/Daft#1843]
**Describe the bug**
Physical plan breaking:
**thread '<unnamed>' panicked at 'no entry found for key', src/daft-plan/src/physical_plan.rs:386:28**

```
File "/Users/andrewgrosser/Library/Caches/pypoetry/virtualenvs/ml-Yqfv2jYI-py3.10/lib/python3.10/site-packages/daft/plan_scheduler/physical_plan_scheduler.py", line 22, in to_partition_tasks
 return physical_plan.materialize(self._scheduler.to_partition_tasks(psets, is_ray_runner))
pyo3_runtime.PanicException: no entry found for key
```

**To Reproduce**
Selecting multiple parquet files from s3 doing daft.read_parquet with native downloader

**Expected behavior**
Working download

**Desktop (please complete the following information):**
 - Mac and Linux

**Additional context**
version 0.2.12
```
Gets: 0, Heads: 0, Lists: 2, BytesRead: 0, AvgGetSize: 0
ScanWithTask [Stage:1]:   0%|          | 0/1 [00:00<?, ?it/s]
thread '<unnamed>' panicked at 'no entry found for key', src/daft-plan/src/physical_plan.rs:386:28
```

I'm blocked by using daft due to the unreliability - please help!

**Comment by samster25** [comment]
Hi @dioptre! Thanks for raising this issue! Could you share a code snippet of causes this error to happen?

Based off the [line number](https://github.com/Eventual-Inc/Daft/blob/854037e172719a2de20d878d975cab7cbdcd541e/src/daft-plan/src/physical_plan.rs#L386C1-L387C1) it looks like it may be an in-memory scan?

**Comment by dioptre** [comment]
I run:
```
daft.read_parquet(
                            [parquets in s3 array], use_native_downloader=True
                        ).to_arrow()
```

**Comment by samster25** [comment]
could you also run 
```
df = daft.read_parquet(
       [parquets in s3 array], 
       use_native_downloader=True
)
df.explain()
```

**Comment by dioptre** [comment]
We get a segmentation fault, so that won't be possible.

**Comment by dioptre** [comment]
Please know that we are getting successes then failures on the same files!
