### ISSUE TITLE
Support columns argument to allow only a subset of columns in parquet file to be accessed

### ISSUE THREAD

**Issue by raghumdani** [Eventual-Inc/Daft#1893]
**Is your feature request related to a problem? Please describe.**
Today, we don't have a way to ensure consistent columns being returned in the daft dataframe when parquet files are read. The `schema_hints` argument doesn't serve this purpose as it disables all schema inference. However, we would like to have schema inference but only specify a subset of columns to be returned as part of dataframe. We do not expect users to delete columns.  

**Describe the solution you'd like**

```python
daft.read_parquet('s3://abcd/abc', columns=['a', 'b'])
```

**Describe alternatives you've considered**
The alternative is to remove columns from the daft dataframe before materializing it. However, this doesn't ensure ordering that we require.

**Additional context**
Another argument that would be helpful is `coerce_int96_timestamp_unit`.

**Comment by samster25** [comment]
Hi @raghumdani,

You can select what columns you'd like to read via a projection
```
df = daft.read_parquet('s3://abcd/abc').select('a', 'b')
```

This will automatically push down the required columns into the parquet read!

You can also use this for a filter + project as well

```
df.where(col("L_SHIPMODE") == "SHIP").select("L_ORDERKEY").explain(True)
```
will result into the following query plan

```
== Optimized Logical Plan ==

* GlobScanOperator
|   Glob paths = [/Users/sammy/b9cbf8a5-d827-48d6-b33d-e932cd623cdb-0.parquet]
|   Coerce int96 timestamp unit = Nanoseconds
|   IO config = S3 config = { Max connections = 8, Retry initial backoff ms = 1000, Connect timeout ms = 30000, Read timeout ms = 30000, Max retries = 25, Retry mode = adaptive, Anonymous = false, Verify SSL = true, Check hostname SSL = true, Requester pays = false }, Azure config = { Anoynmous = false }, GCS config = { Anoynmous = false }
|   Use multithreading = true
|   File schema = L_ORDERKEY#Int64, L_PARTKEY#Int64, L_SUPPKEY#Int64, L_LINENUMBER#Int64, L_QUANTITY#Int64, L_EXTENDEDPRICE#Float64, L_DISCOUNT#Float64, L_TAX#Float64, L_RETURNFLAG#Utf8, L_LINESTATUS#Utf8, L_SHIPDATE#Date, L_COMMITDATE#Date, L_RECEIPTDATE#Date, L_SHIPINSTRUCT#Utf8, L_SHIPMODE#Utf8, L_COMMENT#Utf8
|   Partitioning keys = []
|   Projection pushdown = [L_ORDERKEY]
|   Filter pushdown = col(L_SHIPMODE) == lit("SHIP")
|   Output schema = L_ORDERKEY#Int64
```
 Note that we will only read `L_ORDERKEY` and `L_SHIPMODE` in this case

**Comment by samster25** [comment]
Made an issue for exposing `coerce_int96_timestamp_unit`, good catch there!

https://github.com/Eventual-Inc/Daft/issues/1894

**Comment by jaychia** [comment]
Closing as resolved, but @raghumdani please let us know if you continue to run into issues here
