### ISSUE TITLE
Support regex expressions 

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#1962]
**Is your feature request related to a problem? Please describe.**

Support working with strings with regex expressions. The Ibis docs link 4 useful features:

[re_extract](https://ibis-project.org/reference/expression-strings#ibis.expr.types.strings.StringValue.re_extract)	Return the specified match at index from a regex pattern.
[re_replace](https://ibis-project.org/reference/expression-strings#ibis.expr.types.strings.StringValue.re_replace)	Replace all matches found by regex pattern with replacement.
[re_search](https://ibis-project.org/reference/expression-strings#ibis.expr.types.strings.StringValue.re_search)	Return whether the values match pattern.
[re_split](https://ibis-project.org/reference/expression-strings#ibis.expr.types.strings.StringValue.re_split)	Split a string by a regular expression pattern.

**Comment by ghalimi** [comment]
When you add support for `re_split`, please make sure that you provide support for parentheses in order to preserve the separators.
