### ISSUE TITLE
[Catalogs] [Delta Lake] Add support for writing new Delta Lake tables.

### ISSUE THREAD

**Issue by clarkzinzow** [Eventual-Inc/Daft#1967]
Now that we have read support for Delta Lake, we should add support for writing new Delta Lake tables with Daft.

- https://delta-io.github.io/delta-rs/api/delta_writer/
- https://github.com/delta-io/delta/blob/master/PROTOCOL.md
- https://docs.delta.io/latest/quick-start.html#create-a-table&language-python

**Comment by kevinzwang** [comment]
Completed with #2329
