### ISSUE TITLE
Ignore Spark marker files when performing Parquet Scans

### ISSUE THREAD

**Issue by samster25** [Eventual-Inc/Daft#1987]
When Spark writes parquet files out it creates non-data files as part of the write.
these include `_metadata`, `_common_metadata`, `_SUCCESS`, and `*.crc` checksum files. We should instead filter these out! 

Checkout Pyarrow's implementation for this. https://github.com/apache/arrow/blob/eb7be48ef80fcecea11be29320b244df82f1cc06/python/pyarrow/parquet.py#L556

**Comment by samster25** [comment]
end behavior should allow user to run
```
daft.read_parquet("s3://path/to/data")
```
that has marker files but it is still able to work

**Comment by colin-ho** [comment]
Do we want to be filtering out files like `_metadata`, `_common_metadata`, `_SUCCESS`, and `*.crc`. Or, would it be easier to just filter out files that don't have .parq or .parquet extension (or .csv .json for that matter).

**Comment by samster25** [comment]
I think it would be a better user experience if we filter out the above files. Many systems actually don't write out with a `.parquet` extension or may write out files that look like `.parquet.0000` or something like that
