### ISSUE TITLE
Syntactic sugar for nested getting in column names

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#1994]
**Is your feature request related to a problem? Please describe.**

When retrieving nested columns in structs, we currently rely on the `Expression.struct.get(...)` accessor. However, for deeply nested structs this may get extremely verbose.

Instead, a proposed solution might be to simply use `.` delimiters in the column itself. For example:

```
df = df.with_column("nested_bar", df["foo.bar"])
```

**Comment by samster25** [comment]
👀 @kevinzwang

**Comment by kevinzwang** [comment]
Yeah this is a good idea. Could be applicable to list accessors too(?). When do we want to get this done? Deriving expressions from column names is something we'll eventually get around to in selector expressions, so I'm wondering if it'll make sense to think about these two things together

**Comment by samster25** [comment]
@kevinzwang I think this should much simpler than the selector expressions that we talked about since `col(a.b.c)` will always refer to exactly 1 column. Whereas selector expressions can refer to many.

**Comment by jaychia** [comment]
@kevinzwang to sync with @samster25 on this issue
