### ISSUE TITLE
Fix df.count() behavior to perform count_rows instead

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#1996]
**Is your feature request related to a problem? Please describe.**

When users run `df.count()`, they often expect `df.count_rows()` behavior. Instead, `df.count()` will perform a count aggregation on every column, which is not the intended behavior.

Interestingly, Spark returns an `int` for the `.count()` operation, which is perhaps most intuitive.

See Spark behavior: https://saturncloud.io/blog/counting-rows-in-pyspark-dataframes-a-comprehensive-guide/#counting-rows-using-the-count-function

We should discuss the intended behavior for our `df.count()` operation and implement a fix.

**Comment by universalmind303** [comment]
Coming from other dataframe libraries, this has tripped me up several times.

**Comment by samster25** [comment]
Yeah it's a common confusion point. I think its finally time!
