### ISSUE TITLE
Red lines in Jupyter output

### ISSUE THREAD

**Issue by avriiil** [Eventual-Inc/Daft#2083]
**Describe the bug**
I'm seeing unnecessary/unexplained red warning lines in my jupyter output, see screenshots below.

**To Reproduce**
1. Open a notebook with env/version specs below
2. Create a Daft DataFrame using

```
import datetime

df = daft.from_pydict({
    "integers": [1, 2, 3, 4],
    "floats": [1.5, 2.5, 3.5, 4.5],
    "bools": [True, True, False, False],
    "strings": ["a", "b", "c", "d"],
    "bytes": [b"a", b"b", b"c", b"d"],
    "dates": [datetime.date(1994, 1, 1), datetime.date(1994, 1, 2), datetime.date(1994, 1, 3), datetime.date(1994, 1, 4)],
    "lists": [[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]],
    "nulls": [None, None, None, None],
})
```

3. Run `df.collect()`

**Screenshots**
<img width="902" alt="image" src="https://github.com/Eventual-Inc/Daft/assets/68642378/bcf3f85c-3ac6-4f5d-8ed6-ce880cd3b3da">

<img width="1325" alt="image" src="https://github.com/Eventual-Inc/Daft/assets/68642378/17424c73-1dd7-45fd-b48e-bea23045b66f">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Brave
 - Python 3.11 
 - Daft: 0.2.19
 - Jupyter-lab: 4.1.5
 - tqdm: 4.66.2

**Comment by avriiil** [comment]
I'm not seeing the red line when I run `df.show`:

![image](https://github.com/Eventual-Inc/Daft/assets/68642378/0e8a322e-1481-44cc-bc7b-81662f20e813)

**Comment by samster25** [comment]
Hi @avriiil! Thanks for reporting this! I think it may be an issue with when we show our TQDM progress bars.

@kevinzwang Can you look into why they may be happening?

**Comment by kevinzwang** [comment]
Hey @avriiil! I'm looking into this issue right now. I believe I see similar behavior when I do not have `ipywidgets` installed. Could you check if that package is present in the Python environment of your notebook?

**Comment by avriiil** [comment]
@kevinzwang - I think you might be right. For me the trouble seems to be with `iprogress` specifically. Running `!pip install -U iprogress` solves it.

Should we maybe pin an `iprogress` or `ipywidgets` version in our dependencies so that we solve this for users automatically?

**Comment by kevinzwang** [comment]
Declaring `iprogress` or `ipywidgets` as a dependency doesn't make full sense because it'll only be used by jupyter. Instead my proposed change in #2267 is to keep the warning that tells you to manually install it if it doesn't exist, and change the default behavior when `tqdm` falls back to the non-notebook version to write to stdout instead of stderr when it's in a notebook.
