### ISSUE TITLE
Temporal Arithmetic

### ISSUE THREAD

**Issue by colin-ho** [Eventual-Inc/Daft#2098]
- [ ] Subtraction of timestamps/dates
- [ ] Addition/Subtraction of Duration to dates
- [x] Addition/Subtraction of Duration to timestamps (should be done already)

**Comment by samster25** [comment]
just found out that we did have tests for this but it was being skipped in `tests/dataframe/test_temporals.py::test_temporal_arithmetic` due to the duplicate function name. Enabling skip for this.
to run
`pytest tests/dataframe/test_temporals.py`
