### ISSUE TITLE
Add support for discretizing temporal types, providing "tumbling window groupby" functionality

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#2107]
**Is your feature request related to a problem? Please describe.**

The overall goal of this issue is to enable grouping temporal rows by discrete non-overlapping "windows" (e.g. every minute starting from epoch time).

This can be enabled by providing a function that assigns each datetime value into discrete buckets ("windows") of datetimes, represented by the starting datetime of that window.

```python
df["datetime"].dt.truncate("1 day", start=<defaults to epoch time>)
```

The above expression should return the timestamp of the start of the window that each row falls into.

```
>>> df
+-----------+
| date      |
+-----------+
| 01-01-24  |
| 02-01-24  |
| 03-02-24  |
| 04-02-24  |
| 05-02-24  |
+-----------+

>>> df.with_column("window", df["date"].dt.window(1, unit="month")).show()
+-----------+----------+
| date      | window   |
+-----------+----------+
| 01-01-24  | 01-01-24 |
| 02-01-24  | 01-01-24 |
| 03-02-24  | 01-02-24 |
| 04-02-24  | 01-02-24 |
| 05-02-24  | 01-02-24 |
+-----------+----------+

>>> df.groupby(df["date"].dt.window(1, unit="month")).count()
+-----------+----------+
| date      | count    |
+-----------+----------+
| 01-01-24  | 3        |
| 01-02-24  | 2        |
+-----------+----------+
```

See also:

* Spark: https://spark.apache.org/docs/3.1.3/api/python/reference/api/pyspark.sql.functions.window.html
* Pandas: https://pandas.pydata.org/docs/reference/api/pandas.Grouper.html

**Comment by samster25** [comment]
I think we also may want to add explicit windowing syntactic sugar here instead of using the group-by method
