### ISSUE TITLE
[CHORE] Upgrade PyO3 version to 0.21

### ISSUE THREAD

**Issue by kevinzwang** [Eventual-Inc/Daft#2288]
[PyO3 version 0.21](https://github.com/PyO3/pyo3/releases/tag/v0.21.0) includes several things that we would find useful
- the new Bound API that improves performance over GIL refs
- support for datetime conversions with the abi3 feature, which will eliminate the need for some of the possibly inefficient timestamp conversion code that we currently have

To use these new functionalities we will need to do some refactoring

**Comment by samster25** [comment]
done in https://github.com/Eventual-Inc/Daft/pull/2793
