### ISSUE TITLE
Support for bitwise column operations

### ISSUE THREAD

**Issue by csantosbh** [Eventual-Inc/Daft#2290]
**Ideal solution**
On pyarrow, you can do bitwise filters like this:

```py
import pyarrow as pa
import pyarrow.compute as pc
import pyarrow.dataset as ds

my_bit_mask = pa.scalar(0b100101)
dataset = ds.dataset(parquet_path, format='parquet')

# Equivalent to ds[ds['tags']&my_bit_mask > 0]
mask = pc.greater(pc.bit_wise_and(ds.field('tags'), my_bit_mask), zero).cast(pa.bool_())
filtered = dataset.to_table(filter=mask)
```

Ideally, we should have a similar set of operations for `daft.Expression` objects regarding bitwise operations (at least `and`, `or` and `not`).

**Alternatives**
AFAIK the best alternative right now is to use pyarrow for Table filtering, and interchange the object into a daft DataFrame where daft is stronger.

**Comment by jaychia** [comment]
Hi @csantosbh !

Thanks for making this issue!

Are you thinking of implementing a bitwise `and/or/not` specifically for the Daft `Binary` datatype? That doesn't sound too hard I think 😀

**Comment by samster25** [comment]
@colin-ho can you spec out the daft equivalent expressions for the bitwise section: https://arrow.apache.org/docs/python/api/compute.html#bit-wise-functions

**Comment by samster25** [comment]
@colin-ho actually maybe just the ibis ones are fine for now: https://ibis-project.org/reference/expression-numeric#methods-3

**Comment by colin-ho** [comment]
Created issues here:
https://github.com/Eventual-Inc/Daft/issues/2317
https://github.com/Eventual-Inc/Daft/issues/2318
https://github.com/Eventual-Inc/Daft/issues/2319

**Comment by jaychia** [comment]
Closing this issue in favor of the separate issues created by @colin-ho
