### ISSUE TITLE
error writing parquet: `metadata listed 100000 rows but only read: 100185`

### ISSUE THREAD

**Issue by universalmind303** [Eventual-Inc/Daft#2311]
**Describe the bug**

**To Reproduce**

using the same lineitem file found [here](https://github.com/Eventual-Inc/Daft/issues/2257#issuecomment-2118599555)

```sh
aws s3 cp s3://daft-public-data/testing_data/bad-polars-lineitem.parquet ./lineitem.parquet --no-sign-request
```
```py
import daft

(daft.read_parquet('.lineitem.parquet')
  .limit(100000)
  .write_parquet('lineitem.parquet'))
```

```
DaftCoreException: DaftError::External Parquet file: [file://./lineitem.parquet](file:///lineitem.parquet) metadata listed 100000 rows but only read: 100185
```

**Expected behavior**
able to write the file

**Comment by samster25** [comment]
@universalmind303 I think this bug should now be resolved! I just ran the query and it worked fine.

<img width="452" alt="image" src="https://github.com/user-attachments/assets/fa48d3ca-b6ea-4d7c-a329-e434ba7a248c">
