### ISSUE TITLE
[EXPRESSIONS] `arctan2`

### ISSUE THREAD

**Issue by colin-ho** [Eventual-Inc/Daft#2314]
Compute the two-argument version of arc tangent.https://ibis-project.org/reference/expression-numeric#ibis.expr.types.numeric.NumericValue.atan2

See https://github.com/Eventual-Inc/Daft/pull/2123 for a reference PR

```
df = daft.from_pydict({"a":[1, 2, 3]})
df = df.with_column("atan2", df["a"].atan2(1))
df.show()
```

**Comment by jhasm** [comment]
working on this
