### ISSUE TITLE
[EXPRESSIONS] log with custom base

### ISSUE THREAD

**Issue by colin-ho** [Eventual-Inc/Daft#2315]
`log(base : float)`

Compute the log of a numeric column using a given base, default to base = `e`.

See https://github.com/Eventual-Inc/Daft/pull/2168 for a reference PR

**Comment by jhasm** [comment]
I am starting to work on this one

**Comment by jhasm** [comment]
working on this

**Comment by jhasm** [comment]
Question @colin-ho, why do we want to use an int type if the default value is a float (e = 2.718) ?

**Comment by colin-ho** [comment]
> Question @colin-ho, why do we want to use an int type if the default value is a float (e = 2.718) ?

Should be float, that's my bad.

**Comment by jhasm** [comment]
PR to address this https://github.com/Eventual-Inc/Daft/pull/2324
