### ISSUE TITLE
Bitwise AND

### ISSUE THREAD

**Issue by colin-ho** [Eventual-Inc/Daft#2317]
Compute the bitwise AND of a numeric expression with another expression. Currently the `&` operator only works on boolean expressions: https://github.com/Eventual-Inc/Daft/blob/main/daft/expressions/expressions.py#L242. This can be extended to numeric expressions as well.

Example:
```
df = daft.from_pydict({"a": [0b0000, 0b1100], "b": [0b1111, 0b1111]})
df = df.select(df["a"] & df["b"]) # result = [0b0000, 0b1100]
```

or simply with a scalar value
`df = df.select(df["a"] & 0b1101) # result = [0b0000, 0b1100]`

**Comment by mrutunjay-kinagi** [comment]
@colin-ho  : I would like to contribute to this issue, if its not already done.

**Comment by colin-ho** [comment]
Closed with https://github.com/Eventual-Inc/Daft/pull/2365
