### ISSUE TITLE
Deprecate schema_hints and add schema + infer_schema options to read_json

### ISSUE THREAD

**Issue by colin-ho** [Eventual-Inc/Daft#2328]
Deprecate `schema_hints` and add `schema` + `infer_schema` options to `daft.read_json`. 

`infer_schema : bool = True`: Whether to infer the schema of the JSON, defaults to True.
`schema : Optional[Dict[str, [DataType] = None`: A schema that is used as the definitive schema for the JSON if infer_schema is False, otherwise it is used as a schema hint that is applied after the schema is inferred.

See https://github.com/Eventual-Inc/Daft/pull/2326 for the same changes that were made for `read_csv`

**Comment by GuyPozner** [comment]
I'm on it :)
