### ISSUE TITLE
add df.write_lance 

### ISSUE THREAD

**Issue by universalmind303** [Eventual-Inc/Daft#2364]
**Is your feature request related to a problem? Please describe.**
I'd like to write directly to lance 

**Describe the solution you'd like**
```py
df.write_lance('./lance_tbl')
```

**Describe alternatives you've considered**
I can go through daft -> arrow -> lance, but it'd be alot nicer to be a able to skip that extra step and write directly to a lance table

**Additional context**

**Comment by colin-ho** [comment]
Closed with https://github.com/Eventual-Inc/Daft/pull/2421
