### ISSUE TITLE
groupby limitation - cant get the count of the column upon which grouping is done

### ISSUE THREAD

**Issue by rkunnamp** [Eventual-Inc/Daft#2382]
import daft
from daft import col

data = {
    "category": ["A", "A", "B", "B", "B", "C"],
}

df = daft.from_pydict(data)
df.groupby("category").count("category").show()

DaftCoreException                         Traceback (most recent call last)
[<ipython-input-119-b571f8a3f1e1>](https://localhost:8080/#) in <cell line: 1>()
----> 1 df.groupby("category").count("category").show()

3 frames
[/usr/local/lib/python3.10/dist-packages/daft/logical/builder.py](https://localhost:8080/#) in agg(self, to_agg, group_by)
    199     ) -> LogicalPlanBuilder:
    200         group_by_pyexprs = [expr._expr for expr in group_by] if group_by is not None else []
--> 201         builder = self._builder.aggregate([expr._expr for expr in to_agg], group_by_pyexprs)
    202         return LogicalPlanBuilder(builder)
    203 

DaftCoreException: DaftError::External Unable to create logical plan node.
Due to: DaftError::ValueError Attempting to make a Schema with duplicate field names: category

---

Is there a way to print a table with category, and count of category ?

**Comment by rkunnamp** [comment]
I know of a workaround by creating a copy of the grouped column and using that for counting
df2 =  df.with_column("count" , df["category"])
df2.groupby("category").count("count").show()


Just want to check if that is the recommended way to get the count of a column

**Comment by rkunnamp** [comment]
grouped_df.agg([(grouped_df['category'].alias("count") , "count")]).collect()
seems to be the way to do this

the example currently shown here  https://www.getdaft.io/projects/docs/en/latest/api_docs/groupby.html is slightly misleading

Recommended read is the group by section from here https://www.getdaft.io/projects/docs/en/latest/10-min.html

**Comment by samster25** [comment]
@kevinzwang Let's fix the documentation to make this clearer in the future?
