### ISSUE TITLE
Iceberg Time Travel Support

### ISSUE THREAD

**Issue by syun64** [Eventual-Inc/Daft#2400]
The [IcebergScanOperator](https://github.com/Eventual-Inc/Daft/blob/0f748ed36e3d3fbbc89d566121275cfab8e62010/daft/iceberg/iceberg_scan.py#L132) currently doesn't support time traveling on snapshot IDs.

This issue tracks the work of introducing a [snapshot ID](https://github.com/apache/iceberg-python/blob/a29491af52dc4aff46a325bbaac4a11c2f2bfabc/pyiceberg/table/__init__.py#L1313) argument to the Daft Iceberg APIs to enable scanning data at a specific snapshot ID.

**Comment by jaychia** [comment]
Seems simple enough - we just need to forward the argument to the PyIceberg table during the scan?

```
self._table.scan(limit=limit, snapshot_id=...)
```

How does this interact with `.schema`? Is it possible that Iceberg tables might have different schemas at different snapshots?

**Comment by syun64** [comment]
Yes that's right. The schema id associated with a specific snapshot is stored within the snapshot metadata. When we time travel, we will be [projecting](https://github.com/apache/iceberg-python/blob/a29491af52dc4aff46a325bbaac4a11c2f2bfabc/pyiceberg/table/__init__.py#L1631) the schema associated with that snapshot ID (instead of the current schema ID).
