### ISSUE TITLE
Floor/integer division

### ISSUE THREAD

**Issue by Vince7778** [Eventual-Inc/Daft#2418]
Add support for floor division of integers (`//` operator). Currently you would have to do true division, floor it, then cast from float to int. This is unwieldy and may have precision issues.

Example:
```python
df = daft.from_pydict({"a": [4, 6, 9], "b": [2, 4, 4]})
df = df.select(df["a"] // df["b"])
# should output [2, 1, 2]
```

**Comment by yadomkar** [comment]
Hi @Vince7778  I've tried to add support for floor division with my PR. Looking forward to your feedback.

**Comment by ConeyLiu** [comment]
I will pick this up for a try since @yadomkar is not working on this anymore.

**Comment by samster25** [comment]
Thanks @ConeyLiu! Assigned
