### ISSUE TITLE
Unable to connect Databrick's Unity catalog

### ISSUE THREAD

**Issue by cn-dinakarsundar** [Eventual-Inc/Daft#2433]
**Describe the bug**
ModuleNotFoundError: No module named 'unitycatalog'

**To Reproduce**
1. Go to '...'  Create a standalone python program
2. Click on '....' added this code mentioned in this page https://www.getdaft.io/projects/docs/en/latest/user_guide/integrations/unity-catalog.html
  File "/Users/user/PycharmProjects/daft_project/.venv/lib/python3.11/site-packages/daft/unity_catalog/__init__.py", line 1, in <module>
    from .unity_catalog import UnityCatalog, UnityCatalogTable
  File "/Users/user/PycharmProjects/daft_project/.venv/lib/python3.11/site-packages/daft/unity_catalog/unity_catalog.py", line 6, in <module>
    import unitycatalog
ModuleNotFoundError: No module named 'unitycatalog'

getdaft version used :- 0.2.28
python version 3.11

**Expected behavior**
To connect the databricks unity catalog 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/daft_project/test.py", line 1, in <module>
    from daft.unity_catalog import UnityCatalog
  File "/Users/user/PycharmProjects/daft_project/.venv/lib/python3.11/site-packages/daft/unity_catalog/__init__.py", line 1, in <module>
    from .unity_catalog import UnityCatalog, UnityCatalogTable
  File "/Users/user/PycharmProjects/daft_project/.venv/lib/python3.11/site-packages/daft/unity_catalog/unity_catalog.py", line 6, in <module>
    import unitycatalog
ModuleNotFoundError: No module named 'unitycatalog'

**Comment by jaychia** [comment]
Hey @cn-dinakarsundar thanks for the comment!

We will fix this in our docs and error messages, but to have this work you need the `unitycatalog` pip package. You can install Daft this way to get both: `pip install getdaft[unity]`

Alternatively, you can manually install the `unitycatalog` package like so: `pip install unitycatalog`

Good luck! Let us know if this works in Databricks as well -- we've heard from our partners at Databricks that this might require some private preview functionality in Databricks to allow for credentials vending so if you encounter errors that look like [this](https://github.com/unitycatalog/unitycatalog/issues/2) feel free to let us know!

**Comment by jaychia** [comment]
Docs incoming! https://github.com/Eventual-Inc/Daft/pull/2440

**Comment by vibh3s** [comment]
> Hey @cn-dinakarsundar thanks for the comment!
> 
> We will fix this in our docs and error messages, but to have this work you need the `unitycatalog` pip package. You can install Daft this way to get both: `pip install getdaft[unity]`
> 
> Alternatively, you can manually install the `unitycatalog` package like so: `pip install unitycatalog`
> 
> Good luck! Let us know if this works in Databricks as well -- we've heard from our partners at Databricks that this might require some private preview functionality in Databricks to allow for credentials vending so if you encounter errors that look like [this](https://github.com/unitycatalog/unitycatalog/issues/2) feel free to let us know!

@jaychia  .. How did you resolve the issue 

```
Request to generate access credential for table '2557c82e-*****' from outside of Databricks Unity Catalog enabled compute environment is denied for security. Please contact Databricks support for integrations with Unity Catalog```

Is there any special setting in Databricks required to access UC via daft ?

**Comment by jaychia** [comment]
Yes that is a known issue!

> Good luck! Let us know if this works in Databricks as well -- we've heard from our partners at Databricks that this might require some private preview functionality in Databricks to allow for credentials vending so if you encounter errors that look like https://github.com/unitycatalog/unitycatalog/issues/2 feel free to let us know!

Here is a private preview [form](https://forms.gle/R2mRgbbNCsZrJYmw5) you can use to activate your private preview -- just specify that you want to use Daft with Databricks and someone from Databricks will get in touch with you.
