### ISSUE TITLE
Partition Column in Delta Table using Date

### ISSUE THREAD

**Issue by vibh3s** [Eventual-Inc/Daft#2442]
**Describe the bug**
Not a bug but perhaps a usage question. 

**To Reproduce**
Create a delta table with a Date column and write using partitionBy

**Expected behavior**
Able to use it in a filter

```
    df.where(col("ReceivedDate") == "2024-01-01")
```

I can also see that daft is able to figure out there is a partition column

```
WARNING:root:DeltaLakeScanOperator(None) has partitioning keys = [PartitionField(ReceivedDate#Date)], but no partition filter was specified. This will result in a full table scan.
```

**Screenshots**

daft.exceptions.DaftCoreException: DaftError::External Unable to create logical plan node.
Due to: DaftError::TypeError Cannot perform comparison on types: Date, Utf8
Details:
DaftError::TypeError Cannot perform comparison on types: Date, Utf8

![image](https://github.com/Eventual-Inc/Daft/assets/141128766/f7a7e4ab-0bae-4bd0-983b-d26e574c8887)

**Comment by vibh3s** [comment]
The comparison has to be with a datetime , then it works.  With spark this is not necessary.

In any case , this is not a issue.

```
    .where(col("ReceivedDate") == datetime.date(2024, 1, 1))
```

**Comment by jaychia** [comment]
> The comparison has to be with a datetime , then it works. With spark this is not necessary.
> 
> In any case , this is not a issue.
> 
> ```
>     .where(col("ReceivedDate") == datetime.date(2024, 1, 1))
> ```

Yes indeed, we don't do an "auto-cast" of the string to date yet! This could be an interesting expression optimization to perform though, if we detect that one of the columns is a string we can insert a casting operation.
