### ISSUE TITLE
Daft Sparse Tensor Logical Type

### ISSUE THREAD

**Issue by samster25** [Eventual-Inc/Daft#2494]
* Enable an in memory format for sparse tensors like COO
* This should also work with writing out to parquet.
We can probably export to something like arrows sparse tensor type: 

https://arrow.apache.org/docs/cpp/api/tensor.html#sparse-tensors

**Comment by michaelvay** [comment]
Hi, I am on it :)

**Comment by jaychia** [comment]
@michaelvay let us know how progress is so far! Happy also to pair up and walk you through any parts of the codebase that you might have questions on.
