### ISSUE TITLE
Allow image.decode() to take in an image mode to create a fixed mode image column

### ISSUE THREAD

**Issue by samster25** [Eventual-Inc/Daft#2495]
* imagine we are decoding a column of images that have mixed modes such as RGB and grayscale, the user may want to pass in a fixed mode so we convert everything to a fixed type

something like 

```
df['x'].image.decode(mode"rgb")
```

**Comment by jaychia** [comment]
Definitely a painpoint, I'm running into these issues when attempting to decode images:
<img width="861" alt="image" src="https://github.com/user-attachments/assets/b62c123f-ea3f-4c5d-b08b-61d861608e19">

Seems like our current code just gives up when decoding heterogenous images. We should probably attempt to coerce them into the same mode and dtype
