### ISSUE TITLE
Read specific row group from Parquets

### ISSUE THREAD

**Issue by bchalk101** [Eventual-Inc/Daft#2500]
**Is your feature request related to a problem? Please describe.**
I want to be able to read only specific row groups from a Parquet file. More specifically we have a list of parquet files and corresponding row groups I want to read from them.

**Describe the solution you'd like**
Similar to [Pyarrow method](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetFile.html#pyarrow.parquet.ParquetFile.read_row_group) I would like to be able to specify a row group index which I want to read from a parquet file.

**Describe alternatives you've considered**
I have considered using the Pyarrow method and feeding the table into Daft. The issue is I want to use `into_partitions` and not resolve all the data at once. However, if I could feed a generator into Daft it may solve the issue, as I could use pyarrow together with the generator.

This is related to https://github.com/Eventual-Inc/Daft/issues/2331 and would give us a patch solution until there is a better-supported Daft solution.

**Comment by jaychia** [comment]
Thanks @bchalk101!

Today we do have `daft.read_parquet([...])` which takes in a list of Parquet files. Would a reasonable API for this be:

```
daft.read_parquet(
    ["file1", "file2"],
    row_groups=[[0, 1], [1, 2]],
)
```

This should be fairly easy to support I think

**Comment by bchalk101** [comment]
@jaychia that would be perfect!
