### ISSUE TITLE
Bug with sample->concat->select graph

### ISSUE THREAD

**Issue by danielKapash** [Eventual-Inc/Daft#2510]
**Describe the bug**
When sampling from two dfs, then concatenating the dfs, then selecting columns from resulting df, an exception is thrown:
`Logical op Sample: 0.5 has two inputs, but got one`

**To Reproduce**
```
import daft
x1 = daft.from_pydict({"foo": [1, 2], "bar": [1, 2]}) 
x2 = daft.from_pydict({"foo": [3, 4], "bar": [3, 4]}) 
x1 = x1.sample(0.5) 
x2 = x2.sample(0.5) 
xx = x1.concat(x2) 
xx = xx.select('foo') 
xx.collect()
```

**Expected behavior**
Materialize a df with 0.5 sample from each of the original dataframe, projected on the selected columns.

**Screenshots**
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/61d037d4-66a9-4550-8686-e224db68c645">

**Comment by jaychia** [comment]
Thanks for reporting this! We'll look into the issue shortly :)

**Comment by jaychia** [comment]
This should now be fixed in the latest release @danielKapash !
