### ISSUE TITLE
convert pandas to daft

### ISSUE THREAD

**Issue by cometta** [Eventual-Inc/Daft#2525]
1) may i know how to convert below pandas series to daft? is there similar function for count number of distinct elements in specified axis?
```
df['column_1'].nunique()
```
2)  can advice on below error message
```
df[['column_1', 'column2']].groupby('column1').sum()
```
i get error `daft.exceptions.DaftCoreException: DaftError::External Unable to create logical plan node.
Due to: DaftError::TypeError Invalid argument to sum supertype: Decimal128(7, 2)`

**Comment by jaychia** [comment]
Hi @cometta !

For count_distinct, you can use `DataFrame.distinct`:

```
df.select("column_1").distinct().count_rows()
```
For the second, it seems that you are attempting to sum up a `Decimal` type but it currently isn't allowed. We should allow for that, let me make an issue.

**Comment by jaychia** [comment]
Here's a tracking issue: https://github.com/Eventual-Inc/Daft/issues/2527
