### ISSUE TITLE
Allow summing of Decimal128 types

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#2527]
**Is your feature request related to a problem? Please describe.**

Decimal128 should support the summation aggregation

```
import daft

df = daft.from_pydict({"foo": [1, 1, 2, 2, 3, 3]})
df = df.with_column("foo_decimal", df["foo"].cast(daft.DataType.decimal128(7, 2)))
df = df.sum("foo_decimal")

df.collect()
```

**Comment by amitschang** [comment]
Hey! I'm quite interested in this project and interested in contributing somehow. I thought I could take a go at this issue if OK. I've created a PR that I think technically solves the issue but I wonder if I'm missing something that makes it more generic for this and other aggregations - I made the PR (#2755) draft in case someone would like to take a look and let me know if you think it's on the right track. Thanks!
