### ISSUE TITLE
Bug: Deadlock when iterating two dataframes concurrently 

### ISSUE THREAD

**Issue by EtayLivne** [Eventual-Inc/Daft#2561]
**Describe the bug**
I experience this bug when all of these conditions are true:

1. getdaft version is 0.2.31 (this doesn't happen in any previous version as back as 0.2.25)
2.  I have two active Pytorch IterableDataset objects that I instantiated with to_torch_iter_dataset on two separate Daft dataframes. 
3. Each dataset is split into partitions (I start getting the error very consistently when doing into_partitions(10) in my example below)
4. I use any expression on any column in the dataframes

If I try to iterate both datasets, I get the following stack trace:

```bash
Traceback (most recent call last):                                                                                                                                                      
  File "/path/to/my/code/deadlock.py", line 21, in <module>
    for x, y in zip(iter(ds1), iter(ds2)):
  File "/path/to/my/env/lib/python3.12/site-packages/daft/dataframe/dataframe.py", line 216, in __iter__
    for partition in partitions_iter:
  File "/path/to/my/env/lib/python3.12/site-packages/daft/runners/pyrunner.py", line 216, in run_iter_tables
    for result in self.run_iter(builder, results_buffer_size=results_buffer_size):
  File "/path/to/my/env/benchmark-env/lib/python3.12/site-packages/daft/runners/pyrunner.py", line 211, in run_iter
    yield from results_gen
  File "/path/to/my/env/benchmark-env/lib/python3.12/site-packages/daft/runners/pyrunner.py", line 303, in _physical_plan_to_partitions
    assert len(future_to_task) > 0, "Scheduler deadlocked! This should never happen. Please file an issue."
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Scheduler deadlocked! This should never happen. Please file an issue.
```

**To Reproduce**
In a python env where getdaft==0.2.31 is installed, run the following script:

```python
import daft


def get_dataset():
    df = daft.from_pydict(
        {"numbers": list(range(100))}
    ).into_partitions(10)

    df = df.with_column("numbers", df["numbers"] + 1)
    return df.to_torch_iter_dataset()

    
if __name__ == "__main__":
    ds1 = get_dataset()
    ds2 = get_dataset()
    
    # If we do this we always get the error after < 10 seconds:
    while True:
        for x, y in zip(iter(ds1), iter(ds2)):
            pass
    
    # If we just did this, we'll get the error about 70% of the times we run the code:
    # next(iter(ds1))
    # next(iter(ds2))
        
    # if we do this we never get a deadlock:
    # while True:
    #     for x in iter(ds1):
    #         pass
```

**Expected behavior**
It should be possible to iterate any Daft dataframe regardless of if/which other ones exist.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - python version: 3.12.3 (haven't tested other versions)
 - pytorch version:  2.3.0 (haven't tested other versions)

**Comment by EtayLivne** [comment]
@GuyPozner

**Comment by jaychia** [comment]
Thanks @EtayLivne! We'll take a closer look. This likely has to do with the recent changes to the pyrunner for sharing the underlying threadpool.

**Comment by jaychia** [comment]
Thanks for the repro, it was extremely useful. I've identified the problem, will be talking with the team about a good solution soon.

**Comment by EtayLivne** [comment]
Great to hear and thank you @jaychia !
Looking forward to learning more on this

**Comment by jaychia** [comment]
@EtayLivne this should be fixed on the latest release of Daft! Please feel free to give it a try and let us know if you encounter any more issues.
