### ISSUE TITLE
DaftCoreException: DaftError::External Error joining spawned task: task 136525 panicked

### ISSUE THREAD

**Issue by djouallah** [Eventual-Inc/Daft#2570]
attached reproducible notebook

https://colab.research.google.com/drive/14ZKkEYPWNcDJwy3LmQBA22euB2H_yjXg#scrollTo=HZl-zR2SbbjS

**Comment by samster25** [comment]
@desmondcheongzx or @universalmind303 can one of y'all take a look? Looks like it may be some sort of concurrency bug?

**Comment by djouallah** [comment]
i can't reproduce it using the latest update.
