### ISSUE TITLE
What is daft best practice for resampling a timeseries?

### ISSUE THREAD

**Issue by daveqs** [Eventual-Inc/Daft#2571]
Using Daft built-in expressions, I am able to use dt.truncate on my dataframe's timestamp column and then group by the truncated timestamps. Is this considered a best practice? Or is there another approach that scales better on large dataframes that should be used instead?

For what it's worth, Pandas offer a pandas.dataframe.resample() method, which utilizes the pandas.core.resample.Resampler class under the hood. This appears to be the near-universal recommended solution for Python-based timeseries resampling. Also scipy offers scipy.signal.
resample(). Looking at the Arrow documentation, I found methods to round timestamps, similar to Daft's dt.truncate, but nothing to resample a TimestampArray.

**Comment by jaychia** [comment]
Hi @daveqs !

Are there use-cases in which the truncate method is insufficient? Looking at the resample documentation, I think a groupby on a truncated column should get you mostly what you need. I think we're also open to adding syntactic sugar on top of these operations if there are canonical use-cases for resampling that a higher-level API might make sense for.

**Comment by d4munche3z** [comment]
Is there a optimal way to aggregate on the resampling with this, like in pandas which treats the resampling as bins.

From Pandas API:
`
Upsample the series into 30 second bins.
>>> series.resample('3min', label='right', closed='right').sum()
2000-01-01 00:00:00     0
2000-01-01 00:03:00     6
2000-01-01 00:06:00    15
2000-01-01 00:09:00    15
Freq: 3min, dtype: int64`

**Comment by daveqs** [comment]
> Hi @daveqs !
> 
> Are there use-cases in which the truncate method is insufficient? Looking at the resample documentation, I think a groupby on a truncated column should get you mostly what you need. I think we're also open to adding syntactic sugar on top of these operations if there are canonical use-cases for resampling that a higher-level API might make sense for.

Hi @jaychia thanks for your reply.

My use case involves using Daft to transform an Iceberg table containing timestamped messages consisting of a list of signals (names and values), 1 message per row, for purposes of ML training and inference performed at regularly scheduled intervals. The transformation will yield one (resampled) timestamp per row, signals as columns. The purpose of the resampling is to ensure that I get complete rows of data covering all of my signals, since each message in my source table contains only a subset of the signals. 

My transformation will be performed iteratively as a batch job, and because time behaves nicely and doesn't go backwards (no tachyons in my dataset!), I don't need to worry that any data belonging in a group arriving at time == now needs to be incorporated into groups previously transformed. Also, I know my signals in advance, so I can pass them into the `daft.DataFrame.pivot` method using the `names` argument, which should avoid the need for daft to run a global `distinct` operation. In other words, my use case likely won't stress Daft's ability to groupby truncated timestamps and pivot, as long as my iterations are sufficiently frequent that each batch being transformed is manageable.

That said, I'd find it helpful to know how the daft.Dataframe.groupby and daft.Dataframe.pivot methods work on a DataFrame that is partitioned. Do they get applied partition by partition, or will they be applied globally? (I would like to see them applied partition by partition to enable the operation to be distributed. If they are applied globally, I may decide to use Ray Data's map_batches in order to explicitly batch the groupby and pivot.)

As far as suggestions for syntactic sugar, I don't really care whether I write the resampling transformations out explicitly or use an API that is similar to pandas for resampling. If anything, because I'm also pivoting, writing out the transformations is helpful to see what is really happening.  Many users likely know the pandas resampling syntax already, but this transformation was pretty easy to write once i settled on the truncate/groupby method. The real advantage of adopting a resample API is so that users don't need to think about what operations are happening under the hood (definitely a double edged sword).

Here is the daft code that I wrote to perform the transformation in the description of my use case is unclear, and it runs acceptably fast on initial test cases.  I haven't tried stress testing it yet.
`   
    '''
    Schema of df is:
      sender_id: string
      message_id: string
      timestamp: timestamp[us]
      signals: list<struct<signalname: string, signalvalue: double>>
    '''
    resample_freq = '5 seconds'
    df = df.explode('signals')
    df = df.with_column('signalname', df['signals'].struct.get('signalname'))
    df = df.with_column('signalvalue', df['signals'].struct.get('signalvalue')) 
    df = df.with_column('timestamp_trunc', df['timestamp'].dt.truncate(resample_freq)) 
    wide_df = df.pivot(
        group_by=[daft.col('timestamp_trunc'), daft.col('sender_id')], 
        pivot_col=daft.col('signalname'), 
        value_col=daft.col('signalvalue'),
        agg_fn="mean",
        names=features
    )
`

**Comment by jaychia** [comment]
This looks great @daveqs! From my reading of your code, it should do exactly what you've intended.

For your other questions:
* `daft.Dataframe.groupby` has to be paired with a subsequent `.agg` call. This will perform the aggregation(s) per-group, and the outputted dataframe will be repartitioned according to the group keys.
* `daft.Dataframe.pivot` behaves similarly if provided with the `group_by` argument like you have here. It will partition the dataframe by your provided groups, and perform your specified aggregation over those groups (for each `signalname/signalvalue`)

> If they are applied globally, I may decide to use Ray Data's map_batches in order to explicitly batch the groupby and pivot.)

Could you help me understand this use-case a little better? `daft.Dataframe.groupby` and `daft.Dataframe.pivot` work on the entire dataframe. However, this is already inherently a distributed operation and you do not have to do any explicit parallelization yourself. On a high level, it looks like this:

1. On each partition, perform a local groupby + agg operation (on the groupby keys + pivot key)
2. Shuffle the data across partitions and repartition the data by the groupby + pivot keys
3. Now on each new partition, perform a local groupby + agg operation again (on the groupby keys + pivot key)
4. Now we perform a local pivot operation

**Comment by daveqs** [comment]
> Could you help me understand this use-case a little better? `daft.Dataframe.groupby` and `daft.Dataframe.pivot` work on the entire dataframe. However, this is already inherently a distributed operation and you do not have to do any explicit parallelization yourself. On a high level, it looks like this:
> 
> 
> 
> 1. On each partition, perform a local groupby + agg operation (grouped by `[*groupby_keys, pivot_key]`)
> 
> 2. Shuffle the data across partitions and repartition the data by `groupby_keys`
> 
> 3. Now on each new partition, perform a local groupby + agg operation again (grouped by `[*groupby_keys, pivot_key]`)
> 
> 4. Now we simply perform a local pivot operation

This is exactly what I was looking to understand, thank you!

I will follow up further on Daft slack.

**Comment by jaychia** [comment]
Happy to help!
