### ISSUE TITLE
[SQL] Allow for running of SQL on the Python global() namespace

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#2740]
example: 
```py
df = daft.read_parquet('some/file')

daft.sql('select * from df').collect()
```

**Comment by amitschang** [comment]
I have a small change that implements this within the python `daft.sql` function - by using `inspect`, walking back to the caller frame and getting globals/locals from there to build a catalog in the case that no catalog is supplied. If you think that is a reasonable approach I can prepare a PR. Thanks!

**Comment by universalmind303** [comment]
> I have a small change that implements this within the python `daft.sql` function - by using `inspect`, walking back to the caller frame and getting globals/locals from there to build a catalog in the case that no catalog is supplied. If you think that is a reasonable approach I can prepare a PR. Thanks!


yes feel free to open up a PR! happy to review it.
