### ISSUE TITLE
Naming consistency of `Expression.str.length()` and `Expression.list.lengths()`

### ISSUE THREAD

**Issue by Vince7778** [Eventual-Inc/Daft#2769]
Doesn't make much sense for these to be different. We should change both of these to `.length()`.

**Comment by vicky1999** [comment]
@Vince7778  
could you please let me know the requirements?  According to the description, I think we have to change the name of `Expression.list.lengths()` to `Expression.list.length()`.  Is there any other changes needed?

**Comment by samster25** [comment]
@vicky1999 I think we can add `length` to `Expression.list` and start raising a depreciation warning when `Expression.list.lengths` is called

**Comment by vicky1999** [comment]
@samster25  Can I work on this issue?

**Comment by samster25** [comment]
@vicky1999 assigned!

**Comment by colin-ho** [comment]
Closed with https://github.com/Eventual-Inc/Daft/pull/2942
