### ISSUE TITLE
add support for adding file path as a new column when read from csv/json etc

### ISSUE THREAD

**Issue by djouallah** [Eventual-Inc/Daft#2808]
a common pattern when reading from csv. json etc, is to add a column in the destination table with the files processed already, so the next time you add new csv files, you will not endup with duplicate values, duckdb/polars for example support this function using filename = true

**Comment by kevinzwang** [comment]
Thanks for raising this up! This has been something we have been thinking about adding as well.

**Comment by jaychia** [comment]
@colin-ho could you pick this issue up?

**Comment by jaychia** [comment]
As an added bonus: if we could figure out that the dataframe is partitioned by filename (if no file splitting was performed) that could be really cool.

This could enable easy and cheap data manipulation such as: `df.read_parquet("...", filename=True).groupby("filename").count()`

**Comment by jaychia** [comment]
Example use-case for counting number of distinct rows, grouped by filename: 
<img width="995" alt="image" src="https://github.com/user-attachments/assets/cbdfc6e1-8cd6-4324-8016-0b9dce063f01">

**Comment by djouallah** [comment]
any update on this ?

**Comment by colin-ho** [comment]
Hi @djouallah , sorry for the delay, I'm currently finalizing the PR for this, will let you know once it is ready

**Comment by colin-ho** [comment]
Hey @djouallah, this feature should be ready in the next release!

**Comment by colin-ho** [comment]
This feature is ready in v0.3.9, closing the issue.
