### ISSUE TITLE
enable setting default number of partitions to use for joins in `DaftContext`

### ISSUE THREAD

**Issue by gmweaver** [Eventual-Inc/Daft#2817]
**Is your feature request related to a problem? Please describe.**
`shuffle_aggregation_default_partitions` already exists to set the number of partitions to some sane default for an entire job. It would be helpful to have a similar config for join operations. Those migrating from Spark may be surprised that a migrated job starts OOMing when daft uses one partition for the join.

**Describe the solution you'd like**
Add `shuffle_join_default_partitions` configuration to `DaftContext`.

**Describe alternatives you've considered**
Manually set partitioning via `into_partitions` or `repartition` before `join`.

**Additional context**
N/A

**Comment by samster25** [comment]
Hey @gmweaver, that sounds like a good idea.

We currently have [`shuffle_aggregation_default_partitions`](https://github.com/Eventual-Inc/Daft/blob/main/src/common/daft-config/src/lib.rs#L54) for when we are computing Grouped Aggregations, we could add an additional field for `shuffle_join_default_partitions`

**Comment by samster25** [comment]
@universalmind303 Want to look into taking this ticket?

**Comment by kevinzwang** [comment]
@universalmind303 not sure if this is intended, but this new parameter adds around 10 minutes to our Ray unit test

**Comment by jaychia** [comment]
We will not be taking this on: it's too difficult to come up with a reasonable number here because it's so dependent on the workload.
