### ISSUE TITLE
Rename `DataFrame.where` to `DataFrame.filter`?

### ISSUE THREAD

**Issue by MarcoGorelli** [Eventual-Inc/Daft#2846]
**Is your feature request related to a problem? Please describe.**

The following libraries use `DataFrame.filter`:
- Polars
- Ibis
- PySpark (though they also have `where` as an alias)
- DuckDB in their relational api (https://duckdb.org/docs/api/python/relational_api.html#filtercondition)

Renaming `DataFrame.where` to `DataFrame.filter` (or at least introducing a `filter` alias?) might lower the learning curve?

**Additional context**

**Comment by jaychia** [comment]
Cool -- would love to take a contribution here if you'd like!

I think we're open to exposing an alias and just forward the `*args` and `**kwargs` to `.where`.
