### ISSUE TITLE
mypy error for str.concat

### ISSUE THREAD

**Issue by gmweaver** [Eventual-Inc/Daft#2863]
**Describe the bug**
The typing for `concat` is producing a mypy error.

I am guessing

 `def concat(self, other: str) -> Expression:` 

should be 

`def concat(self, other: Expression) -> Expression:`?

**To Reproduce**
```
df = daft.from_pydict({"x": ["foo", "bar", "baz"], "y": ["a", "b", "c"]})
df.select(daft.col("x").str.concat(daft.col("y"))).collect()
```

`Argument 1 to "concat" of "ExpressionStringNamespace" has incompatible type "Expression"; expected "str"`

**Expected behavior**
No mypy error.

**Comment by samster25** [comment]
I think this should be resolved by @colin-ho PR! Closing this issue for now
