### ISSUE TITLE
[ActorPoolProject] UDFs initialized with the ActorPoolProject do not respect custom init_args/batch_size

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#2899]
**Describe the bug**

We have a TODO in our code to correctly initialize our stateful UDFs with init args and any user-configured batch sizes.

https://github.com/Eventual-Inc/Daft/blob/main/daft/runners/pyrunner.py#L141-L144

We need to make the initialized actors respect these arguments!

**Comment by kevinzwang** [comment]
Resolved in #2956
