### ISSUE TITLE
Implementing hive-style read 

### ISSUE THREAD

**Issue by MisterKloudy** [Eventual-Inc/Daft#2957]
When pyspark saves parquets to a folder on a partition, it creates folders of the partition=some_value. 
When I use daft to read_parquet the parent folder, I would like to get back the columns of the table which were used as partitions.
It would be helpful if we could parse the key=value pairs from the hive partition paths back into columns.

**Comment by colin-ho** [comment]
Closed with https://github.com/Eventual-Inc/Daft/pull/3029 and available in 3.10
