### ISSUE TITLE
SQL: COUNT function not found, but count works

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#2960]
### Describe the bug

<img width="895" alt="image" src="https://github.com/user-attachments/assets/d615ca8b-dd19-46ff-811a-0ae90a04e882">

NOTE: This was produced on Daft version v0.3.4, maybe it's already been fixed?

### Expected behavior

We should probably lowercase the function so that both `COUNT` and `count` work?

### Component(s)

SQL

**Comment by universalmind303** [comment]
this was fixed a few releases ago via https://github.com/Eventual-Inc/Daft/pull/3063
