### ISSUE TITLE
SQL: Column ordering after groupby

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#2961]
### Describe the bug

The column ordering of the output after a groupby and selection on keys seems to be not consistent with what the user specifies

<img width="415" alt="image" src="https://github.com/user-attachments/assets/f1244046-380b-4838-ba80-f3683939d4f7">

### Component(s)

SQL

**Comment by universalmind303** [comment]
resolved via https://github.com/Eventual-Inc/Daft/pull/3177
