### ISSUE TITLE
rename `to_arrow`, `as_arrow`

### ISSUE THREAD

**Issue by andrewgazelka** [Eventual-Inc/Daft#2964]
In the codebase, we have two methods: `to_arrow` and `as_arrow`. These can be potentially confusing due to uncertainty regarding when to use each one. It would be useful to add documentation or perhaps even unify the methods or create a new method that returns a `Cow`.

The reason for this is that `to_arrow` performs an allocation, whereas `as_arrow` returns a reference. Sometimes, you don't actually need to do the allocation. If you return a `Cow`, it can either avoid allocation by returning `Cow::Borrowed`, or perform an allocation when necessary and return `Cow::Owned`.

**Comment by universalmind303** [comment]
there are lots of `to_arrow` methods in the codebase, can you provide more info on which ones you are suggesting changing

**Comment by samster25** [comment]
I added documentation in https://github.com/Eventual-Inc/Daft/commit/02a340445f77e8799b83b7ac4bd590ee9072a682
