### ISSUE TITLE
Group by aggregate list is not implemenented yet. 

### ISSUE THREAD

**Issue by yshvrdhn** [Eventual-Inc/Daft#2981]
**Is your feature request related to a problem? Please describe.**
Yes this a feature request to enable groupby aggregate list. For a common use case described here : 
we are trying to use groupby to do list aggregation essentially we have a column for bbox for our data : [x1,x2,y1,y2] . We want to do groupby and list aggregate using a unique id to get a list of bboxes [[x1,x2,y1,y2],[x1,x2,y1,y2],[x1,x2,y1,y2]] ? however when we use groupby and use list aggregate it raise a list of list not implemented. 
 - https://github.com/Eventual-Inc/Daft/blob/f4d1da2d00d92b8bcc154c2df1b3e47384839492/src/daft-core/src/array/ops/list_agg.rs#L104

**Describe the solution you'd like**
We want to enable the Group by aggregate list that has feature parity with pandas 

**Describe alternatives you've considered**
N/A 

**Additional context**
N/A

**Comment by kevinzwang** [comment]
Will take a look!
