### ISSUE TITLE
SQL: support dot notation for struct accessor

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#2983]
### Describe the bug

<img width="829" alt="image" src="https://github.com/user-attachments/assets/94420789-5300-4cd2-8ec0-a6a02e03e728">

It seems that in a filter our SQL parser treats accessing `.` as accessing a table instead of my intention which is to treat it as accessing a struct field

### Component(s)

SQL

**Comment by universalmind303** [comment]
@jaychia currently our struct access only supports bracket notation, not dot notation. 

give this a try! 

```py
import daft


df = daft.from_pydict(
    {
        "source": [{"database": "db1", "table": "table1"}, {"database": "db2", "table": "table2"}],
        "size": [{"depth": 3}, {"depth": 4}]
    }
)

daft.sql("select source['database'] from df WHERE size['depth'] != 3").collect()

```

**Comment by jaychia** [comment]
Closed, but we need better docs around this I think
