### ISSUE TITLE
tpch query 5 crash daft

### ISSUE THREAD

**Issue by djouallah** [Eventual-Inc/Daft#2988]
### Describe the bug

testing tpch queries using daft, 

### To Reproduce

https://colab.research.google.com/drive/1hIsswquloAd_7E0UzsF6chdyuIPNo081#scrollTo=kQeSmaq5MqRD

### Expected behavior

even if it is not supported, I don't expect a crash 

### Component(s)

SQL

**Comment by jaychia** [comment]
Thanks for providing the Colab! I think we can go off of that to easily see what functionality we still lack and need to prioritize

cc @universalmind303

**Comment by universalmind303** [comment]
TPCH q5 no longer panics! It errors out due to lack of cross join & `INTERVAL` support, but we're actively working on adding support for these!

**Comment by djouallah** [comment]
thanks
