### ISSUE TITLE
add `interval` datatype 

### ISSUE THREAD

**Issue by universalmind303** [Eventual-Inc/Daft#2995]
**Is your feature request related to a problem? Please describe.**
apache arrow has an interval type that would be helpful for various date operations. 

Unlike `duration`, which is an absolute time, the `interval` models types that don't necessarily have a precise duration without the context of a base timestamp (e.g. days can differ in length during day light savings time transitions, or years for leap year)

ex: `1 year`, `1 month`, ...

**Describe the solution you'd like**
```py
df.select(
  (col("date") + daft.interval('1 year')).alias('date_add_year'),
  (col("datetime") + daft.interval('1 year')).alias('datetime_add_year')
)
``` 

**Describe alternatives you've considered**
no alternatives come to mind. 

**Additional context**
Interval type is needed to properly support [tpch q5](https://github.com/Eventual-Inc/Daft/issues/2988)

**Comment by colin-ho** [comment]
closed with https://github.com/Eventual-Inc/Daft/pull/3018
