### ISSUE TITLE
Standard deviation aggregation expression

### ISSUE THREAD

**Issue by kevinzwang** [Eventual-Inc/Daft#2997]
We'd like to have support for computing the standard dev as an aggregation, something along the lines of
```py
# global
df.agg(col("data").std_dev())

# grouped
df.groupby("name").agg(col("data").std_dev())
```
There's an [algorithm for distributed std dev](https://stackoverflow.com/questions/44312818/algorithm-for-distributed-standard-deviation) we can use in order to not need to first compute and broadcast the mean.

**Comment by colin-ho** [comment]
Closed with https://github.com/Eventual-Inc/Daft/pull/3005
