### ISSUE TITLE
Cast SparseTensor and FixedShapeSparseTensor to Python

### ISSUE THREAD

**Issue by sagiahrac** [Eventual-Inc/Daft#3009]
**Current Behavior**
Currently, reading a sparse tensor requires converting it to a dense representation (e.g., Tensor or FixedShapeTensor), or using the default to_arrow implementation for physical struct arrays. At the moment there is no way to iterate directly over daft dataframe without converting the sparse columns to dense representation. This feature would enable native casting to Python, decoupled from future changes to sparse datatypes.

**Proposed Solution**
The desired solution is to allow iteration over a Daft DataFrame containing sparse tensor columns without the need for conversion.

**Alternative Approaches**
An alternative is to use the to_arrow method for casting to Python by default for physical struct arrays. This assumes that the struct inner fields of these types are relevant for the end user.

**Additional context**
A PR implementing this feature is attached.

**Comment by colin-ho** [comment]
Closed with https://github.com/Eventual-Inc/Daft/pull/3010
