### ISSUE TITLE
Sampling always runs with replacement

### ISSUE THREAD

**Issue by ukclivecox** [Eventual-Inc/Daft#3033]
### Describe the bug

Sampling always runs with replacement

### To Reproduce

```
import datetime

df = daft.from_pydict(
    {
        "integers": [1, 2, 3, 4],
        "floats": [1.5, 2.5, 3.5, 4.5],
        "bools": [True, True, False, False],
        "strings": ["a", "b", "c", "d"],
        "bytes": [b"a", b"b", b"c", b"d"],
        "dates": [
            datetime.date(1994, 1, 1),
            datetime.date(1994, 1, 2),
            datetime.date(1994, 1, 3),
            datetime.date(1994, 1, 4),
        ],
        "lists": [[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]],
        "nulls": [None, None, None, None],
    }
)

df.sample(0.5).show()
```

![Screenshot_2024-10-12_15-39-10](https://github.com/user-attachments/assets/ec0235f0-0ac2-4dce-975c-8748514691c6)

### Expected behavior

Allow with_replacement=False

### Component(s)

Expressions

### Additional context

version 0.3.8

Additionally assuming the code is running https://github.com/Eventual-Inc/Daft/blob/c694c9efd30b602e7e4d17962ac4ede545d53f0e/src/daft-table/src/lib.rs#L228-L253 is it possible we could extend sample to take num_rows as this seems to be what is run anyway?

**Comment by colin-ho** [comment]
Hey @ukclivecox , thanks for making this issue. Should be a pretty simple fix, and yes we can extend sample to take num_rows as well!

**Comment by colin-ho** [comment]
Actually, I thought about it a little more, and it won't be trivial to just make sample take a `num_rows` parameter. This is because the data could be split into many partitions, and it won't be possible to take an accurate sample of `num_rows` across partitions without first knowing the length of each partition, which is not trivial to implement. 

The `with_replacement` fix is still possible though, I'm on it right now

**Comment by ukclivecox** [comment]
ok. Thanks for this. As a dev working on datasets for a product/UI its more often I know I want at most X rows rather than some percentage of the dataset. Might be worth opening an issue for a larger change if others think its useful.

**Comment by colin-ho** [comment]
Hey @ukclivecox , the fix has been merged, should be ready in the next relase!

**Comment by ukclivecox** [comment]
Fixed by https://github.com/Eventual-Inc/Daft/pull/3035
