### ISSUE TITLE
null safe equal support in joins

### ISSUE THREAD

**Issue by advancedxy** [Eventual-Inc/Daft#3069]
### Is your feature request related to a problem?

I'm planning to add `intersect` and `intersect all` operator into Daft and get some feature parity with Spark. During the evaluation and code browsing, I noticed that Daft doesn't support null safe equal in joins, it would be great that we can support null safe equal in joins.

P.S: an intersect operator could be rewritten as a semi join with null safe equal.
``` SQL
SELECT a1, a2 FROM t1 INTERSECT SELECT b1, b2 FROM t2
-- is effective the same as
SELECT DISTINCT a1, a2 FROM t1 LEFT SEMI join t2 on a1 <> b1 and a2 <> b2
```

### Describe the solution you'd like

1. add one more parameter to indicate whether the equality condition are null safe or not in joins' DataFrame API and various join ops
2. passing the null safe equality property down to the native execution level
3. build `is_equal` in `src/daft-table/src/ops/joins/hash_join.rs#hash_semi_anti_join` and other related code, makes the execution null safe aware

### Describe alternatives you've considered

Another possible solution is to make join operators to relies on join conditions rather the left_on and right_on keys directly, in that way, null safe equal could be easily added as a new expression.
However, that would require massive code change in daft's current code base and I don't think it's worthy for just null safe equal support.

### Additional Context

I can submit a PR to add null safe equal support if we all agree it's the right time to add.

### Would you like to implement a fix?

No

**Comment by samster25** [comment]
Hi @advancedxy, thanks for making an issue here! @universalmind303 is building out SQL support and @kevinzwang has done lots of work on the semi joins. Would love to hear their thoughts

**Comment by kevinzwang** [comment]
What do you think about doing an outer join + filter instead? Would this work:
```sql
SELECT DISTINCT a1, a2 
  FROM (t1 LEFT OUTER JOIN t2 ON a1 = b1 AND a2 = b2) 
  WHERE (a1 = b1 OR (a1 IS NULL and b1 IS NULL)) AND (a2 = b2 OR (a2 IS NULL and b2 IS NULL))
```

**Comment by kevinzwang** [comment]
I think a null safe equality does make sense. We could make it an expression as well, similar to pyspark's [eqNullSafe](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.Column.eqNullSafe.html). @advancedxy thanks for bringing this up, and feel free to take a stab at implementation yourself first!

**Comment by kevinzwang** [comment]
Thank you @advancedxy !
