### ISSUE TITLE
duplicate columns cause join WHERE expressions to fail

### ISSUE THREAD

**Issue by ukclivecox** [Eventual-Inc/Daft#3072]
### Describe the bug

When there are duplicate columns after a join SQL expressions using table aliases fail and the SQL returns zero rows.

### To Reproduce

```python
# test for left join on multiple tables with rows
import daft

df1 = daft.from_pydict({"idx":[1,2],"val":[10,20]})

df2 = daft.from_pydict({"idx":[3],"score":[0.1]})

df3 = daft.from_pydict({"idx":[1],"score":[0.1]})

df_sql = daft.sql("select * from df1 left join df2 on (df1.idx=df2.idx) left join df3 on (df1.idx=df3.idx) where df3.score > 0").show()
```
This produces:
![Screenshot_2024-10-18_15-43-28](https://github.com/user-attachments/assets/97b67dca-1ece-473b-9b42-a0ea344ff0db)

If one renames one table column so there are no duplicates this works.

```python
# test for left join on multiple tables with rows
import daft

df1 = daft.from_pydict({"idx":[1,2],"val":[10,20]})

df2 = daft.from_pydict({"idx":[3],"score1":[0.1]})

df3 = daft.from_pydict({"idx":[1],"score":[0.1]})

df_sql = daft.sql("select * from df1 left join df2 on (df1.idx=df2.idx) left join df3 on (df1.idx=df3.idx) where df3.score > 0").show()
```
![Screenshot_2024-10-18_15-44-36](https://github.com/user-attachments/assets/ad8a80d4-319c-451e-9746-a3ab332e42b1)

I assume this has to do with renaming of dataframe columns to prefix with `right.`?

### Expected behavior

Table aliases work as expected.

### Component(s)

SQL

### Additional context

Testing with nightly build `0.3.8+dev0019.e4c6f3fa` that has additions for joins from https://github.com/Eventual-Inc/Daft/pull/3066

**Comment by universalmind303** [comment]
removing the sql label as this appears to be the case when joining through the dataframe api as well. 

```py
import daft

df1 = daft.from_pydict({"idx":[1,2],"val":[10,20]})
df2 = daft.from_pydict({"idx":[3],"score":[0.1]})
df3 = daft.from_pydict({"idx":[1],"score":[0.1]})

df = (df1
    .join(df2, on="idx", how="left")
    .join(df3, on="idx", how="left")
    .where(col('score') > 0)
    .collect()
)
df

╭───────┬───────┬─────────┬─────────────╮
│ idx   ┆ val   ┆ score   ┆ right.score │
│ ---   ┆ ---   ┆ ---     ┆ ---         │
│ Int64 ┆ Int64 ┆ Float64 ┆ Float64     │
╞═══════╪═══════╪═════════╪═════════════╡
╰───────┴───────┴─────────┴─────────────╯
(No data to display: Materialized dataframe has no rows)
```

**Comment by ukclivecox** [comment]
I would add that one could make the case that the Dataframe API has different semantics and you need to use the `right.` format for where clauses for duplicate columns. However, for SQL this doesn't make sense so needs to be fixed even if Dataframe API stays the same. But I assume the two ideally would act the same - though with SQL there can be various ways to identify a column in the SQL expression.
