### ISSUE TITLE
read_sql Error: The function 'PERCENTILE_DISC' must havce an OVER clause. code=10753

### ISSUE THREAD

**Issue by athensofamerica** [Eventual-Inc/Daft#3075]
### Describe the bug

When querying SQL server table, we encountered an error.
[ ... ERROR tiberius::tds::stream::token] The function 'PERCENTILE_DISC' must have an OVER clause. code=10753

This doesn't happen for all the table queries, but frequent enough. It seems only happen when read_sql is called with with partition column and number of partitions specified.

This happens on both Linux and Windows system. I was told we can safely ignore this, but it will be nice if it can be fixed. This might be SQL code generation bug for SQL Server (maybe for other database as well). So fix might be pretty easy.

### To Reproduce

Create a SQL database table with large number of rows with an integer column. Query the table using read_sql with SELECT * FROM table. Specify the integer column as the partition column, and a number > 1 as the partition number.

### Expected behavior

return a dafa dataframe with no error

### Component(s)

SQL

**Comment by colin-ho** [comment]
On this

**Comment by colin-ho** [comment]
The fix is in the latest release!

**Comment by athensofamerica** [comment]
Great, thanks @colin-ho!
