### ISSUE TITLE
SSL_CERT_FILE environment variable is set when importing daft

### ISSUE THREAD

**Issue by frederikschubert** [Eventual-Inc/Daft#3097]
### Describe the bug

I am using daft on Ubuntu and have my `SSL_CERT_FILE` variable pointed at `/etc/ssl/certs/ca-certificates.crt`. However when importing daft, the environment variable is set to `/etc/ssl/cert.pem`. This breaks the SSL verification.

### To Reproduce

```
uv init
uv add getdaft
python
...
Python 3.11.9 (main, Aug 14 2024, 05:07:28) [Clang 18.1.8 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ["SSL_CERT_FILE"]
'/etc/ssl/certs/ca-certificates.crt'
>>> import daft
>>> os.environ["SSL_CERT_FILE"]
'/etc/ssl/cert.pem'
```

### Expected behavior

The `SSL_CERT_FILE` should stay as is when importing daft.

### Component(s)

Other

**Comment by samster25** [comment]
Hi @frederikschubert,

We had this override behavior in the past due to a bug in pyarrow. Made a PR to no longer do this.
https://github.com/Eventual-Inc/Daft/pull/3098

**Comment by samster25** [comment]
Merged the fix in @frederikschubert, it should be out in the next release!

**Comment by frederikschubert** [comment]
Great 👍  Thanks for the quick turnaround time! Looking forward to the release :)

**Comment by samster25** [comment]
@frederikschubert This should now be in the latest release now btw!
