### ISSUE TITLE
Idempotent parquet writes with "overwrite" mode

### ISSUE THREAD

**Issue by MisterKloudy** [Eventual-Inc/Daft#3112]
### Is your feature request related to a problem?

Currently all writes only perform new writes and return the paths of the new parquets being written.
This is equivalent to an "append" operation but is inconvenient for creating pipelines which should be idempotent.
Having an "overwrite" mode will allow for idempotent read/writes which can be easily rerun (such as those which are refreshed daily, or need to be rerun due to errors)

### Describe the solution you'd like

Have a parameter/mode for the write_parquet which can overwrite the existing contents of the folder and replace it with the new parquets.

### Describe alternatives you've considered

Deleting the data beforehand using another engine but it's less convenient 

### Additional Context

Similar to mode("overwrite") in pyspark

### Would you like to implement a fix?

No

**Comment by colin-ho** [comment]
On it

**Comment by colin-ho** [comment]
This should be ready in the latest release!
