### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [Eventual-Inc/Daft#320]
`[10-minute tour of Daft](https://getdaft.io/learn/10-min.html)` is broken and also the quickstart one

**Comment by jaychia** [comment]
Thanks for the heads up @FrancescoSaverioZuppichini! I just combed the README and all the links should be fixed now, let us know if you have any questions :)

**Comment by FrancescoSaverioZuppichini** [comment]
@jaychia ❤️
