### ISSUE TITLE
[DOCS] Update incomplete SQL doc pages

### ISSUE THREAD

**Issue by ccmao1130** [Eventual-Inc/Daft#3268]
### Describe the bug

Several doc pages for SQL (API Documentation -> SQL) look like this:
![image](https://github.com/user-attachments/assets/23d04d3c-97f5-4595-a2fb-b79d6a0257be)

Below are all the incomplete SQL docs:
- [AzureConfig](https://www.getdaft.io/projects/docs/en/stable/api_docs/doc_gen/sql_funcs/daft.sql._sql_funcs.AzureConfig.html)
- [GCSConfig](https://www.getdaft.io/projects/docs/en/stable/api_docs/doc_gen/sql_funcs/daft.sql._sql_funcs.GCSConfig.html)
- [HTTPConfig](https://www.getdaft.io/projects/docs/en/stable/api_docs/doc_gen/sql_funcs/daft.sql._sql_funcs.HTTPConfig.html)
- [S3Config](https://www.getdaft.io/projects/docs/en/stable/api_docs/doc_gen/sql_funcs/daft.sql._sql_funcs.S3Config.html)
- [count_matches](https://www.getdaft.io/projects/docs/en/stable/api_docs/doc_gen/sql_funcs/daft.sql._sql_funcs.count_matches.html)
- [hash](https://www.getdaft.io/projects/docs/en/stable/api_docs/doc_gen/sql_funcs/daft.sql._sql_funcs.hash.html)
- [minhash](https://www.getdaft.io/projects/docs/en/stable/api_docs/doc_gen/sql_funcs/daft.sql._sql_funcs.minhash.html)
- [normalize](https://www.getdaft.io/projects/docs/en/stable/api_docs/doc_gen/sql_funcs/daft.sql._sql_funcs.normalize.html)
- [tokenize_decode](https://www.getdaft.io/projects/docs/en/stable/api_docs/doc_gen/sql_funcs/daft.sql._sql_funcs.tokenize_decode.html)
- [tokenize_encode](https://www.getdaft.io/projects/docs/en/stable/api_docs/doc_gen/sql_funcs/daft.sql._sql_funcs.tokenize_encode.html)

And when you search for "normalize", why does it look like this?
![image](https://github.com/user-attachments/assets/d4e2fb2d-56f8-4429-9f47-f833aaa540d5)

### Component(s)

SQL

**Comment by willvo2004** [comment]
I'd like to work on this issue. Having trouble building the docs locally but trying best.

**Comment by universalmind303** [comment]
@willvo2004 if there are any specific issues you are running into while building the docs, feel free to open up separate issues for those!

**Comment by willvo2004** [comment]
Currently having trouble getting documentation changes through; would appreciate direction:
```python
    fn docstrings(&self, _alias: &str) -> String {
        match self {
            Self::EndsWith => "Returns true if the string ends with the specified substring".to_string(),
            Self::StartsWith => "Returns true if the string starts with the specified substring".to_string(),
            Self::Contains => "Returns true if the string contains the specified substring".to_string(),
            .
            .
            .
            Self::Normalize(_) => "Does something cool".to_string(),
        }
    }
```
Changes were made to `src/daft-sql/src/modules/utf8.rs` under the docstrings function.
Changes to documention docstring are to be made here (I could be wrong)

<img width="693" alt="Screenshot 2024-11-13 at 4 34 13 PM" src="https://github.com/user-attachments/assets/b7ecf7ce-084a-4681-b0e0-58d0240edd37">


Running the folllowing build commands for sphinx under daft/docs
```bash
make clean
make html
```
Docstring on documentation site does not appear to be changed and I'm not sure why this is happening. Been trying to trace for a while.
Do I have to change `conf.py`?
