### ISSUE TITLE
daft.context.set_runner_ray() failing in versions 0.3.11 and 0.3.12

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#3285]
### Describe the bug

```
import daft

daft.context.set_ray_runner()
```

We had a regression in behavior in these two versions of Daft, where the above would fail with `RuntimeError: cannot set runner more than once`

### Component(s)

Ray Runner

### Additional context

A fix is being merged for v0.3.13: #side

**Comment by samster25** [comment]
@jaychia @colin-ho is this fixed now?

**Comment by colin-ho** [comment]
Yes
