### ISSUE TITLE
RFC: allow [TEST] label for conventional commit

### ISSUE THREAD

**Issue by andrewgazelka** [Eventual-Inc/Daft#3397]
Right now we only allow
- performance, enhancement, bug, chore, documentation, dependencies

However, sometimes I want to add a PR that only has tests. 
I experience this a lot in Spark Connect when I realize a feature
doesn't need any extra implementation because it has already been
implemented by another PR. 

I want to add the test PR to clarify that we have completed implementing `df.{feature}`.

Proposal: Add a new type of commit that is only for tests. Probably: [TEST]

https://github.com/Eventual-Inc/Daft/blob/ec39dc01ff6879ef2cff43d8f577cacfaaca1cf7/.github/release-drafter.yml#L3-L28
https://github.com/Eventual-Inc/Daft/blob/ec39dc01ff6879ef2cff43d8f577cacfaaca1cf7/.github/workflows/pr-labeller.yml#L50

**Comment by kevinzwang** [comment]
Not particularly opposed to this, but is there a reason you wouldn't include your tests with the relevant feature or bug fix PR? You can also consider using `[CHORE]`

**Comment by jaychia** [comment]
Go for it. Also `[CHORE]` is probably fine.

**Comment by andrewgazelka** [comment]
> Not particularly opposed to this, but is there a reason you wouldn't include your tests with the relevant feature or bug fix PR? You can also consider using `[CHORE]`

https://www.conventionalcommits.org/en/v1.0.0/

> types other than fix: and feat: are allowed, for example [@commitlint/config-conventional](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional) (based on the [Angular convention](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines)) recommends build:, chore:, ci:, docs:, style:, refactor:, perf:, test:, and others.

People often have test (although not required).

Chore is probably the closest we have right now

Here is a subjective cheat sheet someone made https://gist.github.com/Zekfad/f51cb06ac76e2457f11c80ed705c95a3?utm_source=chatgpt.com

They define:

> chore: Changes which doesn't change source code or tests e.g. changes to the build process, auxiliary tools, libraries
> test: Adding missing tests or correcting existing tests

**Comment by jaychia** [comment]
I think I agree with @universalmind303 here. If we want to take any actions, we should probably go with #2867.

Closing in favor of that issue
