### ISSUE TITLE
`to_scan_tasks` properly use async

### ISSUE THREAD

**Issue by andrewgazelka** [Eventual-Inc/Daft#3444]
https://github.com/Eventual-Inc/Daft/blob/b6eee0b5169541b1f5e61f1fc45e76d609360597/src/daft-scan/src/glob.rs#L358

I am going to work on this unless someone else wants to pick it up.

Time Estimate ⌛: ~1hr

**Comment by jaychia** [comment]
This would entail modifying the `ScanOperator` trait, yes?

**Comment by andrewgazelka** [comment]
> This would entail modifying the `ScanOperator` trait, yes?

hmm yes I suppose you are right... do we want to do this?

**Comment by andrewgazelka** [comment]
closing for now (backlog) feel free to reopen. just using `spawn_blocking`

https://github.com/Eventual-Inc/Daft/blob/5e65a85bc0627810dcb2aee6ec9c20d29042d341/src/daft-connect/src/op/execute/root.rs#L37-L41
