### ISSUE TITLE
Support explicit parameterized queries

### ISSUE THREAD

**Issue by MrPowers** [Eventual-Inc/Daft#3496]
### Is your feature request related to a problem?

Daft currently supports this syntax:

```python
def q1(df):
    x = df
    return daft.sql("select id1, sum(v1) as v1 from x group by id1").collect()
```

This is great, but it depends on localhost scope.  

### Describe the solution you'd like

It'd be nice if this syntax was supported as well:

```python
def q1(df):
    return daft.sql("select id1, sum(v1) as v1 from {x} group by id1", x=df).collect()
```

Some other nice to haves that are supported by other query engines like PySpark:

* input sanitization to prevent SQL injection attacks
* smart conversion of types (e.g. a Python date to a SQL date)

### Would you like to implement a fix?

No

**Comment by kevinzwang** [comment]
Hi @MrPowers, we do actually have that, it's exposed as `daft.sql.SQLCatalog`! Docs for it can be found [here](https://www.getdaft.io/projects/docs/en/stable/api_docs/sql.html).

For your example, we would do something like this:
```py
def q1(df):
    return daft.sql(
        "select id1, sum(v1) as v1 from {x} group by id1", 
        catalog=SQLCatalog({"x": df})
    ).collect()
```

**Comment by universalmind303** [comment]
you can also disable the registration of globals if you want to be very explicit about what you are passing in 

```py
import daft
from daft.sql import SQLCatalog

x = make_df()
daft.sql("select * from x", register_globals=False) # this will fail

catalog = SQLCatalog({"x": x})
daft.sql("select * from x", catalog=catalog, register_globals=False) # this will work
```

**Comment by MrPowers** [comment]
Nice, that syntax works, thanks for the help!
