### ISSUE TITLE
spark connect fails when performing a `.show()`

### ISSUE THREAD

**Issue by universalmind303** [Eventual-Inc/Daft#3498]
### Describe the bug

```py
# %%
import daft
from daft.daft import connect_start
from pyspark.sql import SparkSession


server = connect_start()
url = f"sc://localhost:{server.port()}"
session = SparkSession.builder.appName("DaftConfigTest").remote(url).getOrCreate()


session.createDataFrame([("cory", 100)], ["name", "age"]).show()

```

results in `"Error in Daft server: Unsupported relation type: ShowString"`

### Component(s)

Other

### Additional context

It appears that currently our `show` logic exists purely in python. As a prerequisite, we'll need to refactor that logic into rust so that it can be used from spark connect.

**Comment by andrewgazelka** [comment]
> ### Describe the bug
> ```python
> # %%
> import daft
> from daft.daft import connect_start
> from pyspark.sql import SparkSession
> 
> 
> server = connect_start()
> url = f"sc://localhost:{server.port()}"
> session = SparkSession.builder.appName("DaftConfigTest").remote(url).getOrCreate()
> 
> 
> session.createDataFrame([("cory", 100)], ["name", "age"]).show()
> ```
> 
> results in `"Error in Daft server: Unsupported relation type: ShowString"`
> 
> ### To Reproduce
> _No response_
> 
> ### Expected behavior
> _No response_
> 
> ### Component(s)
> Other
> 
> ### Additional context
> It appears that currently our `show` logic exists purely in python. As a prerequisite, we'll need to refactor that logic into rust so that it can be used from spark connect.

also note `createDataFrame` with a string is currently bugged (I am working on fixing it)

**Comment by universalmind303** [comment]
> Can we just use Display rust impl for now?

no, the logical plan display is equivalent to `df.explain()`. 

`df.show()` shows a small sample of the materialized dataset similar to `df.limit(10).collect()`

**Comment by universalmind303** [comment]
@andrewgazelka I can take on this one.

**Comment by universalmind303** [comment]
closed via https://github.com/Eventual-Inc/Daft/pull/3560
