### ISSUE TITLE
Get length of dataframe

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#358]
**Is your feature request related to a problem? Please describe.**

We should provide a `len(df)` to show the total number of rows in a dataframe

## Proposal

```python
df = DataFrame.read_*(...)

# Throws an error: dataframe not yet materialized
len(df)

# Executes a plan, performs a global aggregation and pulls the result to the driver as an integer
df.count_rows()

# After materialization of a DataFrame, len now works.
# It merely queries each partition for its size metadata, and returns
# the sum of all sizes (does not run any computation on partitions)
df.collect()
len(df)
```

**Comment by jaychia** [comment]
As discussed in https://github.com/Eventual-Inc/Daft/discussions/476

`len(df)` will throw an error on an unmaterialized DataFrame informing users to either use `.count_rows()` or collect the DataFrame first.

**Comment by Asrst** [comment]
hi @jaychia, I started working on this. Can i contribute to this issue?

**Comment by jaychia** [comment]
> hi @jaychia, I started working on this. Can i contribute to this issue?

Yes, of course! Please make a PR and link the issue.
