### ISSUE TITLE
async UDFs

### ISSUE THREAD

**Issue by mplemay** [Eventual-Inc/Daft#3624]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I would like `async` function support for UDFs

### Would you like to implement a fix?

No

**Comment by kevinzwang** [comment]
Hi @mplemay, what is your use case for an async UDF?

**Comment by mplemay** [comment]
> Hi @mplemay, what is your use case for an async UDF?

@kevinzwang I was specifically interested in calling an web api, but it would generally be useful for any blocking IO operations

**Comment by kevinzwang** [comment]
Hi @mplemay, I don't believe async UDFs would offer any performance advantages. Each UDF already runs on an individual thread or process, and the Python async runtime does not easily integrate with Daft's work scheduling, we would essentially run it as a blocking function anyway.

For IO operations, I would recommend either using a synchronous library such as [requests](https://pypi.org/project/requests/), or calling `asyncio.run()` if you need to run async code.

Closing this issue for now

**Comment by mplemay** [comment]
Makes sense @kevinzwang and thank you for the detailed response.
