### ISSUE TITLE
ModuleNotFoundError: No module named 'unitycatalog 

### ISSUE THREAD

**Issue by djouallah** [Eventual-Inc/Daft#3629]
### Describe the bug

pipeline stopped working today with this error ?  I don't use unity is this a hard dependency now ?

      5 from typing import Callable
      6 from urllib.parse import urlparse
      8 import unitycatalog
     10 from daft.io import AzureConfig, IOConfig, S3Config
     13 @dataclasses.dataclass(frozen=True)
     14 class UnityCatalogTable:

ModuleNotFoundError: No module named 'unitycatalog

### Component(s)

Other

**Comment by jaychia** [comment]
Should not be! This looks like an unintentional bug. 

Let me take a look

**Comment by jaychia** [comment]
Could you show the full stacktrace? I see that it might be coming from `df.write_deltalake` from this change: https://github.com/Eventual-Inc/Daft/commit/dd2dc23a8f6c38c4ac1caf79c0edae29252c7276

**Comment by desmondcheongzx** [comment]
Do you know which line of code in the pipeline triggered this error? Unity catalog is imported lazily so it should only be imported when something that depends on it is used

**Comment by jaychia** [comment]
I think we likely will want to cut a release if #3630 fixes the issue. I'll let @kevinzwang and @raunakab handle it from here.

**Comment by djouallah** [comment]
cheers, it fixed the issue
