### ISSUE TITLE
Error UX: Public APIs should do input validation

### ISSUE THREAD

**Issue by xcharleslin** [Eventual-Inc/Daft#465]
Where possible, public API methods should do basic input validation immediately and raise exceptions with descriptive and actionable messages in their string value field.

The error messages should be:

1. What the user provided (value and context: what parameter in what function)
2. Why Daft couldn't handle it
3. How the user can fix this error (if not already clear)

**Comment by jaychia** [comment]
Done for `DataFrame` public APIs
