### ISSUE TITLE
More descriptive Expression errors

### ISSUE THREAD

**Issue by xcharleslin** [Eventual-Inc/Daft#466]
Error use case: User types in an invalid expression in a Daft function call. e.g. `df.select("wrong_column")`

- **Operation on nonexistent column**: `df.select("fake_column")`
  - Current error: `ValueError: Could not find expr by name "fake_column"`
  - Proposed improvement: Use user-facing terminology "column" or "expression" and mention the `select` context.

- **Column expression raises exception**: `df.select(df["A"] + df["H"])`
  - Current error: e.g. `TypeError: unsupported operand type(s) for +: 'int' and 'MyObj'` or `TypeError: unsupported operand type(s) for +: 'int' and 'MyObj'`
  - Proposed improvement: Mention the column context (mention `"A"` and `"H"`). Mention the `select` context.

**Comment by jaychia** [comment]
Closed for inactivity
