### ISSUE TITLE
More descriptive error: `write` when target is existing file

### ISSUE THREAD

**Issue by xcharleslin** [Eventual-Inc/Daft#469]
For `write_*`, the method expects a **folder** parameter. If the user gives an existing file instead of folder, the error is 

`FileExistsError: [Errno 17] Cannot create directory './file.csv': non-directory entry exists. Detail: [errno 17] File exists`

This is not unworkable, but could possibly be more descriptive and actionable. The user could be confused why we are talking about creating directories when they gave a perfectly valid filename.

**Comment by jaychia** [comment]
Closing this in favor of #1422
