### ISSUE TITLE
Error improvement wishlist for Beta

### ISSUE THREAD

**Issue by xcharleslin** [Eventual-Inc/Daft#472]
New things to implement for all public APIs:
- https://github.com/Eventual-Inc/Daft/issues/464
- https://github.com/Eventual-Inc/Daft/issues/465

Some low hanging fruit:
- https://github.com/Eventual-Inc/Daft/issues/469
- https://github.com/Eventual-Inc/Daft/issues/470
- https://github.com/Eventual-Inc/Daft/issues/507

**Comment by jaychia** [comment]
Closing as most of them are done - to reopen if necessary
