### ISSUE TITLE
Add `+` operator to strings for concatenation

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#493]
# Summary

A Pythonic way of concatenating two strings is by overloading the `__add__` operator. Users unfamiliar with Daft will attempt to do this and currently will encounter a type exception. This should be a fairly simple overload to alias the `str.concat` expression when called.

## Proposal

```python
from daft import lit, DataFrame

df = DataFrame.from_pydict({"foo": ["a", "b", "c"]})
df = df.with_column("foo_concat_lit", df["foo"] + "bar")
df = df.with_column("foo_concat_lit_reverse", "bar" + df["foo"])
df = df.with_column("foo_concat_col", df["foo"] + df["foo"])
df.collect()

# +----------+------------------+--------------------------+------------------+
# | foo      | foo_concat_lit   | foo_concat_lit_reverse   | foo_concat_col   |
# | STRING   | STRING           | STRING                   | STRING           |
# +==========+==================+==========================+==================+
# | a        | abar             | bara                     | aa               |
# +----------+------------------+--------------------------+------------------+
# | b        | bbar             | barb                     | bb               |
# +----------+------------------+--------------------------+------------------+
# | c        | cbar             | barc                     | cc               |
# +----------+------------------+--------------------------+------------------+
# (Showing first 3 of 3 rows)
```

### Discussed in https://github.com/Eventual-Inc/Daft/discussions/478

<div type='discussions-op-text'>

<sup>Originally posted by **jaychia** January 19, 2023</sup>
# Summary

More operations on Strings

See: https://ibis-project.org/docs/3.0.2/api/expressions/strings/ for operations that could be useful.

**Please comment on this Discussion if there are any operations that you would like prioritized!**
</div>

**Comment by khuara17** [comment]
Hi  @jaychia , I would like to work on this, Would you be able to provide me with guidance to get started and a little bit more info on the request, please?

**Comment by jaychia** [comment]
Thanks @khuara17 !

I added a little more information into the issue above with a few test cases.

A little guidance:

1. The `ADD` operator is implemented as a "Numeric Binary Op" [currently](https://github.com/Eventual-Inc/Daft/blob/main/daft/execution/operators.py#L325). The type matrix that it uses is `_BinaryNumericalTM `, which does not allow for string types to be added together. We should extend the type matrix for this operation to include the `(str, str) => str` type signature so that it will allow adding of two string expressions.
2. After modifying the type signature of `ADD`, we will need to modify the [implementation of the kernel itself](https://github.com/Eventual-Inc/Daft/blob/main/daft/runners/blocks.py#L900) in our ArrowDataBlock. Currently, it is a simple wrapper of PyArrow's `add` kernel, but I believe their add kernel does not support adding string types, so we'll have to write a custom wrapper to corner-case strings and redirect the call to the [same kernel that we use for `.str.concat`](https://github.com/Eventual-Inc/Daft/blob/main/daft/runners/blocks.py#L867-L868)

Let me know if you have trouble getting started! You can get in touch with us on Discord: https://discord.gg/eByWAQwTaP

**Comment by Asrst** [comment]
Hi @khuara17, still planning to work on this?

**Comment by samster25** [comment]
We're in the middle of doing a refactor of our compute backend (and moving it to rust). The kernel for this was added in https://github.com/Eventual-Inc/Daft/pull/437 and https://github.com/Eventual-Inc/Daft/pull/531 and will be enabled shortly (1-2 weeks)

**Comment by jaychia** [comment]
Done as part of Rust execution engine refactor
