### ISSUE TITLE
[Feature] Drop NA rows

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#572]
# Summary

Drop NA/Null rows - convenience wrapper for filtering rows where certain columns contain null or NaN values.

## Proposal

```
df.drop_na()  # drops rows where any column contains Null/NaN values
df.drop_na("x", "y")  # drops rows where columns x or y contain Null/NaN values
```

### Discussed in https://github.com/Eventual-Inc/Daft/discussions/483

<div type='discussions-op-text'>

<sup>Originally posted by **jaychia** January 19, 2023</sup>
# Summary

Convenience method to drop rows where certain columns are NA

We need to be careful here about null semantics!

## Proposal

We can have this alias `df.where(~(df["c1"].is_null() | df["c2"].is_null() ...))`</div>

**Comment by FelixKleineBoesing** [comment]
@jaychia Can be closed now :)

**Comment by jaychia** [comment]
Thanks @FelixKleineBoesing !!
