### ISSUE TITLE
[Bug] Join optimizer broken for pushdowns to only the right side

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#594]
**Describe the bug**
When joins are followed by a Projection (or LocalAggregation) that only accesses columns from the `right` dataframe, the optimizer will break.

**To Reproduce**

The unit test on the branch #590  breaks (run: `pytest -k test_projection_join_pruning`), but here is a simple reproducing case.

```python
df = DataFrame.from_pydict({"a": [1, 2, 3], "b": [4, 5, 6]})
df.join(df, on="a").select("right.b").collect()
```

**Comment by jaychia** [comment]
This is a much deeper-rooted problem with regard to identification of expressions using only-names vs a unique ID.

Will be addressed later after our Rust refactor.

**Comment by clarkzinzow** [comment]
Closing this as fixed!
