### ISSUE TITLE
[Bug] Repartitioning might no-op on aliased columns

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#596]
**Describe the bug**

Our partitioning schemes currently keep track of which column the DataFrame is partitioned on by column name.

However, this breaks when we alias a different column with the current partitioning scheme's column name:

```
df = DataFrame.from_pydict({"a": [1, 2, 3], "b": [4, 5, 6]})
df = df.repartition(2, "a").select(col("b").alias("a")).repartition(2, "a")
```

In the above example, the second repartition will be a no-op because the optimizer believes that the Dataframe is already partitioned into 2 partitions by column "a", even though the new column "a" is actually an aliased "b".

## Reproduce

Unskip the test and run `pytest -k test_repartition_alias` on #590

**Comment by clarkzinzow** [comment]
I believe that this was fixed in https://github.com/Eventual-Inc/Daft/pull/1372, closing.
