### ISSUE TITLE
[Visualization] Allow for scrollable HTML div for text overflow

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#621]
**Is your feature request related to a problem? Please describe.**

We currently truncate text with an ellipsis if it is too long, in the HTML display of our dataframe. I would prefer if we allow for a scrollable HTML div instead, so that a user can read the text if they wish.

This is obtrusive when trying to visualize the data - the only other real way is to pull data down via `.to_pydict()` and view it as a Python string.

**Comment by darkcheftar** [comment]
Hey @jaychia 
I want to work on the issue.
