### ISSUE TITLE
Write a guide on partitioning

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#840]
Write a guide to enumerate key concepts around partitioning:

```
Increasing the number of partitions in your DataFrame has the following effects:

1. Increase the amount of parallelism available to your workload (since more partitions can be processed in parallel)
2. Decrease the efficiency of "global operations" such as a sort, aggregation or join (since data is split on a finer level of granularity and more shuffling of data is required)
3. Decrease the peak memory utilization of processing each partition (since your partitions will be smaller and take less memory to process per-partition)
```

Also, how to think about partitioning schemes, partition columns and ways to repartition a dataframe.

When this is done, we should also link the document in our `Key Concepts` quickstart doc.

**Comment by hannydevelop** [comment]
Hi @jaychia is this still open? can I work on it?

**Comment by jaychia** [comment]
Hi @hannydevelop yes! Please feel free to come up with a proposal, and we are also happy to chat about it in person. Come talk to us on the [Slack](https://join.slack.com/t/dist-data/shared_invite/zt-1t44ss4za-1rtsJNIsQOnjlf8BlG05yw)

**Comment by hannydevelop** [comment]
hello @jaychia great, I'll work on this now

**Comment by ghalimi** [comment]
More information on partitioning would be great!
