### ISSUE TITLE
Truncate display for large tables

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#901]
**Is your feature request related to a problem? Please describe.**

When a table is large (e.g. >100 columns), the table becomes very difficult to read in a REPL (see screenshot)

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/17691182/236893585-9646339f-46ae-4639-a940-32bfc8f0ecde.png">

We should truncate the columns (similar to polars/Pandas) for readability.

This might still be ok to view in HTML since users can scroll around in a notebook environment!

**Comment by roopeshsn** [comment]
Hi, @jaychia! I would like to work on this issue.

**Comment by jaychia** [comment]
Hi, thanks @roopeshsn!

Let me populate the Issue with more context soon. I would hold off on this until we have our repr centralized to using our Rust `Table::Format` code. Right now the DataFrame repr is a separate codepath from the Table repr.

cc @xcharleslin

**Comment by jaychia** [comment]
Hi @roopeshsn!

This issue can be worked on now :) we've migrated all our display code to `Table::format` so there will be less redundant work.

**Comment by roopeshsn** [comment]
Thanks, @jaychia! I'll begin my work to fix the issue.
