### ISSUE TITLE
Fix handling of newlines in rows when parsing CSV

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#902]
**Is your feature request related to a problem? Please describe.**

When parsing CSVs, newlines inside of rows cause issues because we use PyArrow to parse the CSVs.

PyArrow has a `newlines_in_values` option that needs to be `True` when parsing such CSVs. However, the caveat is that it claims that performance will be lower because it is unable to perform multithreading, and this option defaults to `False`. (https://arrow.apache.org/docs/python/generated/pyarrow.csv.ParseOptions.html)

**Requirements**

We should be able to parse CSVs with newlines in the rows if they are properly quoted (e.g. `...,"foo\nbar",...`).

It is likely that PyArrow uses the newline delimiter to understand how to split up a file for multithreaded reading. There could be potential workarounds here - for example, using a count of the column delimiter instead to split the files.

**Comment by samster25** [comment]
When do we need this? Generally we should try to avoid this option since it will prevent multithreaded reads or "reading into multiple partitions" that we talked about.

**Comment by jaychia** [comment]
The following is a valid CSV and we will encounter them in datasets that have long-form text as a column:

```
foo,bar
1,baz
2,baz
1, "Dear John,
How are you?
"
```

Currently, our code will fail to parse this because it thinks that `How are you?` is its own row. Passing in the `newlines_in_values=True` option to PyArrow does allow us to read such files, but will slow down reading operations.

**Comment by jaychia** [comment]
Closing as we will be moving to native reads of CSV in #1422
