### ISSUE TITLE
[Extension Types] Support pyarrow extension types on the Ray runner.

### ISSUE THREAD

**Issue by clarkzinzow** [Eventual-Inc/Daft#933]
User-provided extension types need to be registered on all Python Ray workers, even for non-UDF operations, since we always materialize a Python-land (i.e. pyarrow) view of the partition as a `daft.Table`. See this CI failure [here](https://github.com/Eventual-Inc/Daft/actions/runs/4969702964/jobs/8893075688?pr=899).

A few options come to mind:
1. Use a private Ray API like `ray._private.worker.run_function_on_all_workers()` to register the extension type on all workers. This has a bunch of race condition issues since this function runs on the import thread in Ray, which can run concurrently with task execution and task argument deserialization.
2. Use a [runtime environment](https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#runtime-environments) + a semi-private [plugin API](https://github.com/ray-project/ray/blob/e2c6d9bb974d84ca2ad9a76ff0237f1d762a3b48/python/ray/_private/runtime_env/plugin.py#L23-L99) to register the extension type on all workers. Not sure how well this will work.
3. Create a Python-level Daft context singleton that's passed to every Ray task in the Ray runner, and keep a registry of user-provided extension types that we need to ensure are registered on Python workers; this context singleton will end up being useful for a bunch of different things. We ultimately had to do this for Ray Datasets for a few different features.

**Comment by samster25** [comment]
This should work now
