### ISSUE TITLE
Better `List` type repr in dataframes

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#994]
**Is your feature request related to a problem? Please describe.**

The currently `List` repr in dataframes is unnecessarily verbose, especially after an aggregation:

<img width="555" alt="image" src="https://github.com/Eventual-Inc/Daft/assets/17691182/794d08ed-3127-4b27-8118-dd51bd4bfd50">

We should just omit the child field's name here.

**Comment by fool1280** [comment]
Hi, I'd like to take on this issue. May I ask for some hints? Thank you!

**Comment by jaychia** [comment]
Hi @fool1280!

This has to do with the `repr` of our list DataType. It should likely be a pretty simple fix to trace where the repr calls into the Rust display method here: https://github.com/Eventual-Inc/Daft/blob/main/src/datatypes/dtype.rs#L404

**Comment by khandelwalarvind26** [comment]
Hey @jaychia I am working on this issue, I have traced the call to repr. Can you please share the code to create the aggregated datatypes for testing? Thanks!

**Comment by jaychia** [comment]
Yup, any multi-partition aggregation would give you this issue!

```python
import daft

df = daft.from_pydict({"foo": [1, 2, 3]}).into_partitions(2)
df = df.agg([("foo", "list")])
df.collect()
```
